"""Guards for apply_type_corrections.py: its retype rules, its ADDITIONS
insertion, and `main()`'s verdict on the file.

Every fixture exists in both table layouts (one entry per line as generated,
and rustfmt's multi-line form as committed), because a pass that works on only
one fails silently on the other. The slice is sorted by (group_path,
field_name) and declares its length, so an insertion must keep both true.
"""
import contextlib
import io
import re
import sys
import tempfile
import unittest
from pathlib import Path


sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import apply_type_corrections as atc  # noqa: E402


#: A synthetic table holding every real ADDITION between bookends that sort
#: before and after all of them; derived from ADDITIONS, so it cannot go stale.
BOOKENDS = [
    ("/Game/AAA.AAA_C", "Alpha"),
    ("/Script/ShooterGame.AmmoComponent", "MagazineAmmo"),
    ("/Script/ShooterGame.OwnerExclusivePlayerInfo", "RoundNumber"),
    ("/Script/ShooterGame.ZzzTailComponent", "Stripes"),
]
GROUPS = sorted(BOOKENDS + [(g, f) for g, f, _t in atc.ADDITIONS])


def rustfmt_type(field_type):
    """A braced type the way rustfmt lays it out inside an entry: one field
    per line, each with a trailing comma. A bare variant comes back as is."""
    if "{" not in field_type:
        return field_type
    head, _brace, rest = field_type.partition("{")
    fields = [part.strip() for part in rest.rstrip("} ").split(",") if part.strip()]
    inner = "".join(f"            {part},\n" for part in fields)
    return f"{head.rstrip()} {{\n{inner}        }}"


def render_table(rows, one_line=False, braced_multiline=False, handles=None):
    """A table.rs holding `rows`, each `(group, field, full FieldType)`.

    The default layout is the committed rustfmt'd one; `one_line` is the one
    extract_descriptors.py emits. Rows carry their own type because an
    Int32-only table cannot show the `"Int32" in "FieldType::UInt32"` bug.
    `braced_multiline` breaks braced types over lines as rustfmt does, where a
    one-line literal replace would no longer match. With `handles` (possibly
    empty) the file is complete -- true header lines and slice lengths, and
    OVERLAY_HANDLE_TABLE after the last entry; without it the header lines are
    placeholders and the file ends with OVERLAY_TABLE.
    """
    if one_line:
        body = "".join(
            f'    OverlayEntry {{ group_path: "{g}", field_name: "{f}", '
            f"field_type: {t} }},\n"
            for g, f, t in rows
        )
        handle_body = "".join(
            f'    OverlayHandleEntry {{ group_path: "{g}", handle: {h}, '
            f'field_name: "{f}" }},\n'
            for g, h, f in handles or ()
        )
    else:
        body = "".join(
            "    OverlayEntry {\n"
            f'        group_path: "{g}",\n'
            f'        field_name: "{f}",\n'
            f"        field_type: {rustfmt_type(t) if braced_multiline else t},\n"
            "    },\n"
            for g, f, t in rows
        )
        handle_body = "".join(
            "    OverlayHandleEntry {\n"
            f'        group_path: "{g}",\n'
            f"        handle: {h},\n"
            f'        field_name: "{f}",\n'
            "    },\n"
            for g, h, f in handles or ()
        )
    table = f"pub static OVERLAY_TABLE: [OverlayEntry; {len(rows)}] = [\n{body}];\n"
    if handles is None:
        return "// 0 entries from 0 groups.\n// Raw/Custom: 0, Skip: 0, Typed: 0.\n" + table
    raw = sum(1 for _g, _f, t in rows if t == "FieldType::Raw")
    skip = sum(1 for _g, _f, t in rows if t == "FieldType::Skip")
    return (
        "// GENERATED by tools/extract_descriptors.py -- do not edit by hand.\n"
        f"// {len(rows)} entries from {len({g for g, _f, _t in rows})} groups.\n"
        f"// Raw/Custom: {raw}, Skip: {skip}, Typed: {len(rows) - raw - skip}.\n"
        f"\n{table}\n"
        f"pub static OVERLAY_HANDLE_TABLE: [OverlayHandleEntry; {len(handles)}] = [\n"
        f"{handle_body}"
        "];\n"
    )


ADDED_KEYS = {(g, f) for g, f, _t in atc.ADDITIONS}
WITHOUT = [(g, f, "FieldType::Int32") for g, f in GROUPS if (g, f) not in ADDED_KEYS]
N_ADDED = len(atc.ADDITIONS)


class AdditionsTests(unittest.TestCase):
    def test_every_addition_names_a_real_field_type(self):
        """Each addition is well formed (`FieldType::X`) and appears once."""
        seen = set()
        for group, field, ftype in atc.ADDITIONS:
            # Every group today is a full UE path; a bare replay-declared name
            # would be valid too. Empty or non-alphanumeric-leading is not.
            self.assertTrue(group.startswith("/") or group[0].isalpha(), group)
            self.assertTrue(field and not field.startswith("_"), field)
            self.assertTrue(ftype.startswith("FieldType::"), ftype)
            self.assertNotIn((group, field), seen, f"duplicate {group}/{field}")
            seen.add((group, field))

    def test_additions_stay_the_narrow_exception(self):
        """Pinned exactly, so adding or removing an ADDITION updates this
        number in the same commit. The evidence for each lives at its entry in
        apply_type_corrections.py; check_docs measures the count too.
        """
        self.assertEqual(len(atc.ADDITIONS), 142, atc.ADDITIONS)

    def test_handle_additions_stay_the_narrow_exception(self):
        """The same pin for the handle -> name additions (empty; docs/DATA.md
        says why the mechanism stays). Each (group, field_name) must also be an
        ADDITION, or the name would type nothing."""
        self.assertEqual(len(atc.HANDLE_ADDITIONS), 0, atc.HANDLE_ADDITIONS)
        addition_keys = {(g, f) for g, f, _t in atc.ADDITIONS}
        for group, _handle, field in atc.HANDLE_ADDITIONS:
            self.assertIn(
                (group, field), addition_keys,
                f"handle addition {group}/{field} has no matching ADDITION type",
            )

    def test_every_addition_is_also_verified(self):
        """An addition absent from EXPECTED would apply once and never be
        checked. The whole `FieldType::...` is asserted: a variant name alone
        cannot tell `FieldType::Int32` from `FieldType::UInt32`."""
        for group, field, ftype in atc.ADDITIONS:
            self.assertIn((group, field, ftype), atc.EXPECTED)

    def _assert_inserted_in_order(self, content):
        keys = [(g, f) for g, f, _ in atc.parse_entries(content)]
        self.assertEqual(keys, sorted(keys), "table must stay sorted")
        for group, field, _ in atc.ADDITIONS:
            self.assertIn((group, field), keys)
        self.assertEqual(len(keys), len(WITHOUT) + N_ADDED)
        return keys

    def test_inserts_into_the_formatted_layout(self):
        out, n = atc.apply_additions(render_table(WITHOUT))
        self.assertEqual(n, N_ADDED)
        self._assert_inserted_in_order(out)

    def test_inserts_into_the_freshly_generated_one_line_layout(self):
        """The layout the script actually meets when run in documented order."""
        out, n = atc.apply_additions(render_table(WITHOUT, one_line=True))
        self.assertEqual(n, N_ADDED)
        self._assert_inserted_in_order(out)

    def test_is_idempotent(self):
        once, n1 = atc.apply_additions(render_table(WITHOUT))
        twice, n2 = atc.apply_additions(once)
        self.assertEqual((n1, n2), (N_ADDED, 0))
        self.assertEqual(once, twice)

    def test_verify_reports_a_missing_addition(self):
        problems = atc.verify(render_table(WITHOUT))
        self.assertTrue(
            any("LoadoutValue" in p and "BaseTeamState" in p for p in problems),
            problems,
        )

    def test_verify_passes_once_added(self):
        out, _ = atc.apply_additions(render_table(WITHOUT))
        remaining = [p for p in atc.verify(out) if "BaseTeamState" in p]
        self.assertEqual(remaining, [])

    def test_declared_length_is_resynced(self):
        out, _ = atc.apply_additions(render_table(WITHOUT))
        out = atc.resync_table_len(out)
        self.assertIn(
            f"[OverlayEntry; {len(WITHOUT) + len(atc.ADDITIONS)}]", out
        )

    def test_both_generated_header_lines_are_recounted(self):
        """`// N entries from M groups.` counts the descriptors; ADDITIONS add
        entries and, for a group no descriptor declares, whole groups."""
        out, _ = atc.apply_additions(render_table(WITHOUT))
        out, lines = atc.rewrite_header(out)
        n_groups = len({g for g, _f in GROUPS})
        self.assertEqual(lines[0],
                         f"// {len(GROUPS)} entries from {n_groups} groups.")
        self.assertIn(lines[0], out)
        # The two lines must agree with each other and with the slice length.
        buckets = [int(n) for n in re.findall(r": (\d+)", lines[1])]
        self.assertEqual(sum(buckets), len(GROUPS))
        self.assertIn(f"[OverlayEntry; {len(GROUPS)}]",
                      atc.resync_table_len(out))

    def test_rewriting_the_header_is_idempotent(self):
        out, _ = atc.apply_additions(render_table(WITHOUT))
        once, lines1 = atc.rewrite_header(out)
        twice, lines2 = atc.rewrite_header(once)
        self.assertEqual((once, lines1), (twice, lines2))

    def test_a_missing_header_line_is_a_hard_failure(self):
        """Not a silent skip: a table without the line was not generated by
        extract_descriptors.py, and recounting it would say nothing."""
        out, _ = atc.apply_additions(render_table(WITHOUT))
        with self.assertRaises(SystemExit):
            atc.rewrite_header(out.replace("// 0 entries from 0 groups.\n", ""))

    def test_appends_past_the_end_of_the_slice(self):
        """An entry sorting after every existing one is the new tail, spliced
        before OVERLAY_TABLE's `];` (the first in the final split block), not
        refused. The insertion tests above never reach this path: every
        ADDITION sorts before their ZzzTail bookend."""
        earlier = [("/AAAAA.First", "Field", "FieldType::Int32")]
        out, n = atc.apply_additions(render_table(earlier))
        self.assertEqual(n, len(atc.ADDITIONS))
        keys = [(g, f) for g, f, _ in atc.parse_entries(out)]
        self.assertEqual(keys, sorted(keys), "table must stay sorted after append")
        self.assertEqual(len(keys), 1 + len(atc.ADDITIONS))
        # OVERLAY_TABLE's closing bracket is still present exactly once.
        self.assertEqual(out.count("];\n"), 1)


class RetypeTests(unittest.TestCase):
    """`retype` keys on each block's OWN entry, never on text elsewhere: the
    last split block also holds OVERLAY_HANDLE_TABLE, which repeats group paths
    and field names."""

    GROUP = "/Script/ShooterGame.ReplayEffectComponent:ReplayPlayContinuousEffectAtLocation"

    def table(self, last_type):
        return render_table([
            (self.GROUP, "AllianceFilter", "FieldType::EnumRemainingBits"),
            (self.GROUP, "AllianceFilterX", "FieldType::EnumRemainingBits"),
            ("/Script/ShooterGame.ZzzTailComponent", "Stripes", last_type),
        ], handles=[(self.GROUP, 28, "AllianceFilter")])

    def test_only_the_exact_entry_changes(self):
        # The tail entry carries the old type too, and the handle table after
        # it names the same group and field -- the shape a substring pass
        # would misread as "the last entry is AllianceFilter".
        source = self.table("FieldType::EnumRemainingBits")
        out, n = atc.retype(source, atc.exact_retype(
            self.GROUP, "AllianceFilter",
            "FieldType::EnumRemainingBits", "FieldType::EnumByte"))
        self.assertEqual(n, 1)
        self.assertEqual(
            [(f, t) for _g, f, t in atc.parse_entries(out)],
            [("AllianceFilter", "FieldType::EnumByte"),
             ("AllianceFilterX", "FieldType::EnumRemainingBits"),
             ("Stripes", "FieldType::EnumRemainingBits")])

    def test_an_already_corrected_table_changes_nothing(self):
        out, n = atc.retype(self.table("FieldType::Float"), atc.exact_retype(
            self.GROUP, "AllianceFilter", "FieldType::EnumByte", "FieldType::Raw"))
        self.assertEqual(n, 0)
        self.assertEqual(out, self.table("FieldType::Float"))

    def test_an_unexpected_count_is_a_hard_failure(self):
        with self.assertRaises(SystemExit):
            atc.retype(self.table("FieldType::Float"), atc.exact_retype(
                self.GROUP, "AllianceFilter",
                "FieldType::EnumRemainingBits", "FieldType::EnumByte", expected=2))

    def test_a_braced_retype_changes_the_entry_it_counts(self):
        """The count claims an entry changed, so it must have: rustfmt breaks a
        braced type over lines, where its one-line literal is not there to
        replace. A change that cannot be made in place is refused."""
        group = atc.GAME_OBJECT_BYTE_ROTATOR_GROUPS[0]
        rep = ("FieldType::RepMovement {{ rotation: RotatorQuantization::{}, "
               "location: VectorQuantization::{} }}")
        short_whole = rep.format("ShortComponents", "RoundWholeNumber")
        byte_whole = rep.format("ByteComponents", "RoundWholeNumber")
        for one_line in (True, False):
            with self.subTest(one_line=one_line):
                source = whole_table(UNCORRECTED_GAME_OBJECT_ROTATORS,
                                     one_line=one_line, braced_multiline=not one_line)
                out, n = atc.retype(source, atc.exact_retype(
                    group, "ReplicatedMovement", short_whole, byte_whole))
                types = {(g, f): t for g, f, t in atc.parse_entries(out)}
                self.assertEqual((n, types[(group, "ReplicatedMovement")]),
                                 (1, byte_whole))
                with self.assertRaises(SystemExit):
                    atc.retype(source, atc.exact_retype(
                        group, "ReplicatedMovement", short_whole,
                        rep.format("ByteComponents", "RoundTwoDecimals")))


#: A weapon group of the shape the "215"/"216" pass discovers for itself.
WEAPON_GROUP = "/Game/Equippables/Guns/Rifles/Vandal.Vandal_C"
WEAPON_ROWS = [
    (WEAPON_GROUP, "215", "FieldType::EnumRemainingBits"),
    (WEAPON_GROUP, "216", "FieldType::EnumRemainingBits"),
]


def whole_table(overrides=None, drop=(), one_line=False, braced_multiline=False,
                extra=(), handles=()):
    """A complete table.rs that satisfies every correction, minus `overrides`.

    Derived from EXPECTED, so it cannot go stale. `overrides` maps an EXPECTED
    key to the type the file carries INSTEAD ("regenerated but never
    corrected"), `drop` leaves keys out, `extra` adds `(group, field, type)`
    rows and `handles` fills OVERLAY_HANDLE_TABLE. Header lines and slice
    lengths are true, so `main()` fails for the reason under test.
    """
    overrides = overrides or {}
    rows = [
        (g, f, overrides.get((g, f), t))
        for g, f, t in list(atc.EXPECTED) + WEAPON_ROWS
        if (g, f) not in drop
    ] + list(extra)
    return render_table(sorted(rows), one_line, braced_multiline, list(handles))


#: The mutations below are BUCKET-NEUTRAL: each swaps one typed variant for
#: another, so the header lines are identical either way and `--check` fails
#: for the reason under test, not a header. SmokeScreen's rule rewrites each
#: entry in both layouts, so a file carrying ShortComponents is correctable.
UNCORRECTED_SMOKESCREEN = {
    ("SmokeScreen", "ReplicatedMovement"):
        "FieldType::RepMovement { rotation: RotatorQuantization::ShortComponents, "
        "location: VectorQuantization::RoundWholeNumber }",
}
#: Gekko's Wingman as the generator emits it: whole units, the default every
#: `RepMovement` entry starts from.
UNCORRECTED_SEEKER_NADE = {
    (atc.SEEKER_NADE_GROUP, "ReplicatedMovement"):
        "FieldType::RepMovement { rotation: RotatorQuantization::ShortComponents, "
        "location: VectorQuantization::RoundWholeNumber }",
}
#: The five AGameObject smoke/zone classes as the generator emits them: the
#: bare `.ReplicatedMovement()` builder default, short rotator components.
UNCORRECTED_GAME_OBJECT_ROTATORS = {
    (group, "ReplicatedMovement"):
        "FieldType::RepMovement { rotation: RotatorQuantization::ShortComponents, "
        "location: VectorQuantization::RoundWholeNumber }"
    for group in atc.GAME_OBJECT_BYTE_ROTATOR_GROUPS
}
#: A correction whose entry is gone, as if the descriptors stopped declaring
#: it: no rule can create it, so it is DEAD in either layout. Pass as `drop=`.
DEAD_TIME_REMAINING = [("TimedBomb.TimedBomb_C", "TimeRemainingToExplode")]
#: The first line of each FAILED section `main()` prints.
DEAD_HEADER = "corrections are missing from"
UNCORRECTED_HEADER = "the file was never corrected"


class MainOnDiskTests(unittest.TestCase):
    """`main()` on a real file: `--check` must judge the file on disk, not the
    corrected copy, so a correctable file nobody corrected fails CI."""

    def setUp(self):
        self._real_table = atc.TABLE_RS
        self._temp = tempfile.TemporaryDirectory()
        self.path = Path(self._temp.name) / "table.rs"
        atc.TABLE_RS = self.path
        self._real_argv = sys.argv

    def tearDown(self):
        atc.TABLE_RS = self._real_table
        sys.argv = self._real_argv
        self._temp.cleanup()

    def run_main(self, source, *args):
        """`(exit_code, stdout, stderr)` for one main() run over `source`."""
        self.path.write_text(source, encoding="utf-8")
        sys.argv = ["apply_type_corrections.py", *args]
        out, err = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
            code = atc.main()
        return code, out.getvalue(), err.getvalue()

    def test_a_correct_table_still_passes(self):
        code, out, err = self.run_main(whole_table(), "--check")
        self.assertEqual(code, 0, err)
        self.assertIn("verified", out)

    def test_a_correctable_but_uncorrected_file_fails(self):
        """The rules CAN fix it, and nobody ran them."""
        code, _out, err = self.run_main(
            whole_table(UNCORRECTED_SMOKESCREEN), "--check"
        )
        self.assertEqual(code, 1, "--check must not pass an uncorrected file")
        self.assertIn("ShortComponents", err)

    def test_a_dead_pattern_still_fails_loudly(self):
        """A correction that cannot be applied at all."""
        code, _out, err = self.run_main(
            whole_table(drop=DEAD_TIME_REMAINING), "--check"
        )
        self.assertEqual(code, 1)
        self.assertIn("TimeRemainingToExplode", err)
        self.assertIn(DEAD_HEADER, err)

    def test_the_two_failure_modes_are_distinguishable(self):
        """One table can trip BOTH at once -- a correction whose entry is gone
        and one the rules apply in memory -- and neither report may hide the
        other."""
        code, _out, err = self.run_main(
            whole_table(UNCORRECTED_SMOKESCREEN, drop=DEAD_TIME_REMAINING), "--check")
        self.assertEqual(code, 1)
        self.assertIn("TimeRemainingToExplode", err)
        self.assertIn("ShortComponents", err)
        self.assertIn(DEAD_HEADER, err)
        self.assertIn(UNCORRECTED_HEADER, err)

    def test_check_writes_nothing(self):
        source = whole_table(UNCORRECTED_SMOKESCREEN)
        self.run_main(source, "--check")
        self.assertEqual(self.path.read_text(encoding="utf-8"), source)

    def test_unknown_flag_is_rejected_and_cannot_fall_into_write_mode(self):
        source = whole_table(UNCORRECTED_SMOKESCREEN)
        self.path.write_text(source, encoding="utf-8")
        sys.argv = ["apply_type_corrections.py", "--chekc"]
        with contextlib.redirect_stdout(io.StringIO()), \
                contextlib.redirect_stderr(io.StringIO()):
            with self.assertRaises(SystemExit) as raised:
                atc.main()
        self.assertEqual(raised.exception.code, 2)
        self.assertEqual(self.path.read_text(encoding="utf-8"), source)

    def test_final_verification_failure_leaves_the_file_byte_identical(self):
        """A partially correctable run must not publish before verify passes."""
        source = whole_table(UNCORRECTED_SMOKESCREEN, drop=DEAD_TIME_REMAINING)
        code, _out, _err = self.run_main(source)
        self.assertEqual(code, 1)
        self.assertEqual(self.path.read_text(encoding="utf-8"), source)

    def test_applying_then_checking_passes(self):
        """The documented cure: run without --check, and --check goes green."""
        code, _out, err = self.run_main(whole_table(UNCORRECTED_SMOKESCREEN))
        self.assertEqual(code, 0, err)
        sys.argv = ["apply_type_corrections.py", "--check"]
        with contextlib.redirect_stdout(io.StringIO()), \
                contextlib.redirect_stderr(io.StringIO()):
            self.assertEqual(atc.main(), 0)

    def test_the_seeker_nade_location_level_is_corrected_in_both_layouts(self):
        """The one two-decimal class: its rule fires in both layouts, and
        `--check` refuses a file still carrying the whole-unit default."""
        want = (
            "FieldType::RepMovement { rotation: RotatorQuantization::ShortComponents, "
            "location: VectorQuantization::RoundTwoDecimals }"
        )
        for one_line in (True, False):
            with self.subTest(one_line=one_line):
                source = whole_table(UNCORRECTED_SEEKER_NADE, one_line=one_line)
                code, _out, err = self.run_main(source, "--check")
                self.assertEqual(code, 1, "--check must not pass the default")
                self.assertIn("RoundWholeNumber", err)
                code, _out, err = self.run_main(source)
                self.assertEqual(code, 0, err)
                types = {
                    (g, f): t for g, f, t in
                    atc.parse_entries(self.path.read_text(encoding="utf-8"))
                }
                self.assertEqual(
                    types[(atc.SEEKER_NADE_GROUP, "ReplicatedMovement")], want)

    def test_the_game_object_rotators_are_corrected_in_both_layouts(self):
        """The five AGameObject classes read byte rotator components: the rule
        fires in both layouts (a one-line literal replace would silently miss
        the rustfmt'd one), and `--check` refuses the short default on any."""
        want = (
            "FieldType::RepMovement { rotation: RotatorQuantization::ByteComponents, "
            "location: VectorQuantization::RoundWholeNumber }"
        )
        self.assertEqual(len(atc.GAME_OBJECT_BYTE_ROTATOR_GROUPS), 5)
        for one_line in (True, False):
            with self.subTest(one_line=one_line):
                source = whole_table(UNCORRECTED_GAME_OBJECT_ROTATORS,
                                     one_line=one_line, braced_multiline=not one_line)
                if not one_line:
                    self.assertIn(
                        "            rotation: RotatorQuantization::ShortComponents,\n",
                        source, "the fixture must carry rustfmt's multi-line form")
                code, _out, err = self.run_main(source, "--check")
                self.assertEqual(code, 1, "--check must not pass the short default")
                for group in atc.GAME_OBJECT_BYTE_ROTATOR_GROUPS:
                    self.assertIn(group, err)
                code, _out, err = self.run_main(source)
                self.assertEqual(code, 0, err)
                types = {
                    (g, f): t for g, f, t in
                    atc.parse_entries(self.path.read_text(encoding="utf-8"))
                }
                for group in atc.GAME_OBJECT_BYTE_ROTATOR_GROUPS:
                    self.assertEqual(types[(group, "ReplicatedMovement")], want, group)
                # The one short-rotator class the table keeps is untouched.
                self.assertIn(
                    "ShortComponents",
                    types[(atc.SEEKER_NADE_GROUP, "ReplicatedMovement")])

    def test_a_partially_corrected_rotator_set_is_a_hard_failure(self):
        """Two of five still short is neither "fresh" nor "done": refuse it."""
        groups = atc.GAME_OBJECT_BYTE_ROTATOR_GROUPS
        partial = {k: v for k, v in UNCORRECTED_GAME_OBJECT_ROTATORS.items()
                   if k[0] in groups[:2]}
        with self.assertRaises(SystemExit):
            atc.retype(whole_table(partial), atc.GAME_OBJECT_ROTATOR_RETYPE)
        out, n = atc.retype(whole_table(), atc.GAME_OBJECT_ROTATOR_RETYPE)
        self.assertEqual(n, 0, "an already corrected table must change nothing")
        self.assertEqual(out, whole_table())

    def test_an_uncorrected_weapon_group_is_reported(self):
        """EXPECTED names only the five non-weapon "215"/"216" groups; the
        weapon rule discovers its targets, so its result is checked from the
        table, or it could no-op in silence."""
        raw_weapons = {(WEAPON_GROUP, "215"): "FieldType::Raw"}
        code, _out, err = self.run_main(whole_table(raw_weapons), "--check")
        self.assertEqual(code, 1, "an uncorrected weapon group must be caught")
        self.assertIn(WEAPON_GROUP, err)

    def test_a_table_with_no_weapon_groups_at_all_is_reported(self):
        """The other shape of the same silence: discovery finds no weapon
        group at all, and a count of 0 would be the only trace, so the
        absence itself fails."""
        code, _out, err = self.run_main(
            whole_table(drop=[(WEAPON_GROUP, "215"), (WEAPON_GROUP, "216")]),
            "--check",
        )
        self.assertEqual(code, 1)
        self.assertIn("/Game/Equippables/", err)

    def test_the_summary_counts_the_weapon_expectations_too(self):
        """The summary line is a claim about how much was checked."""
        _code, out, _err = self.run_main(whole_table(), "--check")
        self.assertIn(f"all {len(atc.EXPECTED) + len(WEAPON_ROWS)} ", out)

    def test_the_handle_table_cannot_retype_the_last_entry(self):
        """A rule that looked for its group or field anywhere in the last block
        would read a handle entry (OVERLAY_HANDLE_TABLE sits there) as the last
        entry's and retype it, unreported: verify() checks EXPECTED keys only
        and the exit code is 0. Each tail carries the type a rule rewrites; the
        handle names either a field a rule has keyed on (the tail's field is
        unrelated) or a group the rule accepts (the tail's field is the rule's).
        """
        short_whole = (
            "FieldType::RepMovement { rotation: RotatorQuantization::ShortComponents, "
            "location: VectorQuantization::RoundWholeNumber }"
        )
        damage = "/Script/ShooterGame.DamageableComponent:MulticastNotifyDamage_"
        smoke = "/Game/Characters/X/Projectile_X_SmokeScreen.Projectile_X_SmokeScreen_C"
        state_machine = "/Script/ShooterGame.EquippableStateMachineComponent"
        # (tail field, tail type, handle group, handle field)
        cases = [
            ("Unrelated", "FieldType::Raw", damage + "Base", "EquippableUsed"),
            ("Unrelated", "FieldType::Raw", damage + "Point", "DamageOrigin"),
            ("Unrelated", "FieldType::Skip", "/Game/Characters/X/Pawn_X.Pawn_X_C",
             "ReplayLastTransformUpdateTimeStamp"),
            ("Unrelated", short_whole, smoke, "ReplicatedMovement"),
            ("Unrelated", short_whole, atc.SEEKER_NADE_GROUP, "ReplicatedMovement"),
            ("Unrelated", "FieldType::Raw", state_machine, "TransitionContext"),
            ("ReplicatedMovement", short_whole, smoke, "Unrelated"),
            ("ReplicatedMovement", short_whole, atc.SEEKER_NADE_GROUP, "Unrelated"),
            ("TransitionContext", "FieldType::Raw", state_machine, "Unrelated"),
            # The real handle table names this group, and the fixture's own
            # entry is already corrected, so a stray retype of the tail would
            # count exactly the rule's expected 1 and raise nothing.
            ("DeathMontageEffectOverride", "FieldType::Raw", damage + "Base",
             "Unrelated"),
        ]
        for tail_field, tail_type, handle_group, handle_field in cases:
            tail = ("zzz/Tail.Tail_C", tail_field)
            for one_line in (True, False):
                with self.subTest(tail=tail_field, group=handle_group,
                                  field=handle_field, one_line=one_line):
                    source = whole_table(
                        extra=[(*tail, tail_type)],
                        handles=[(handle_group, 7, handle_field)],
                        one_line=one_line, braced_multiline=not one_line)
                    # The fixture must put the handle table after the tail
                    # row, or this passes without testing anything.
                    self.assertEqual(
                        [(g, f) for g, f, _t in atc.parse_entries(source)][-1], tail)
                    handle_part = source.partition("OVERLAY_HANDLE_TABLE")[2]
                    self.assertIn(f'group_path: "{handle_group}"', handle_part)
                    self.assertIn(f'field_name: "{handle_field}"', handle_part)
                    code, _out, err = self.run_main(source)
                    self.assertEqual(code, 0, err)
                    types = {
                        (g, f): t for g, f, t in
                        atc.parse_entries(self.path.read_text(encoding="utf-8"))
                    }
                    self.assertEqual(types[tail], atc.normalize_type(tail_type))


class VerifyMatchesTheWholeTypeTests(unittest.TestCase):
    """`verify` compares whole types: a substring test passes the wrong
    signedness and the wrong byte variant (see EXPECTED)."""

    def _wrong_type(self, group, field, wrong):
        """One-entry table declaring a real EXPECTED key at the wrong type."""
        return render_table([(group, field, wrong)])

    @staticmethod
    def _about(problems, field):
        """Only the problems naming `field` -- the rest of EXPECTED is absent
        from a one-entry table and would drown the assertion message."""
        return [p for p in problems if field in p]

    def test_a_wrong_signedness_is_reported(self):
        table = self._wrong_type(
            "/Script/ShooterGame.BaseTeamState", "LoadoutValue", "FieldType::UInt32"
        )
        about = self._about(atc.verify(table), "LoadoutValue")
        self.assertTrue(
            any("UInt32" in p for p in about),
            f"UInt32 where Int32 is required must be reported; got {about}",
        )

    def test_a_wrong_byte_variant_is_reported(self):
        group = ("/Game/Characters/_Core/Comp_AbilityStatisticsReplicator"
                 ".Comp_AbilityStatisticsReplicator_C")
        field = "Slot_12_22D571914FAFD5F0EBD400B7E2F28B36"
        about = self._about(
            atc.verify(self._wrong_type(group, field, "FieldType::EnumByte")), field
        )
        self.assertTrue(
            any("EnumByte" in p for p in about),
            f"EnumByte where Byte is required must be reported; got {about}",
        )

    def test_a_pre_existing_wrong_type_is_skipped_by_additions_and_reported(self):
        """ADDITIONS skips a key already present (overwriting a declaration the
        descriptors make would be worse), so a key there at the WRONG type must
        be reported instead."""
        table = self._wrong_type(
            "/Script/ShooterGame.BaseTeamState", "LoadoutValue", "FieldType::UInt32"
        )
        out, added = atc.apply_additions(table)
        self.assertEqual(added, len(atc.ADDITIONS) - 1, "the present key is skipped")
        about = self._about(atc.verify(out), "LoadoutValue")
        self.assertTrue(
            about, "the skipped, wrong-typed key must be reported; nothing was"
        )

    def test_the_committed_types_still_verify(self):
        """The exact comparison passes the committed table."""
        problems = atc.verify(atc.TABLE_RS.read_text(encoding="utf-8"))
        self.assertEqual(problems, [])


if __name__ == "__main__":
    unittest.main()
