"""Guards for the ADDITIONS pass in apply_type_corrections.py.

The corrections in that script rewrite entries that already exist; the
additions pass INSERTS entries the C# descriptors cannot declare. Insertion has
two failure modes the replacements do not:

* the table exists in two layouts -- one entry per line as
  extract_descriptors.py emits it, and the rustfmt'd multi-line form that gets
  committed. The script's own docstring records that a newline-anchored helper
  silently matched nothing on a freshly generated table, which is exactly when
  it is supposed to run. An insertion pass that only works on one layout fails
  the same way.
* the slice is sorted by (group_path, field_name) and declared with an explicit
  length. Inserting at the wrong position breaks `tests::overlay::table_is_sorted`
  and forgetting the length breaks the build.
"""
import contextlib
import io
import re
import sys
import tempfile
import unittest
from pathlib import Path


sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import apply_type_corrections as atc  # noqa: E402


#: A synthetic table containing every real ADDITION plus bookends that sort
#: before and after all of them. DERIVED from ADDITIONS rather than hardcoded:
#: the first version of this file pinned "the two entries" as a literal and
#: broke the moment a third was added, which is noise rather than signal.
BOOKENDS = [
    ("/Game/AAA.AAA_C", "Alpha"),
    ("/Script/ShooterGame.AmmoComponent", "MagazineAmmo"),
    ("/Script/ShooterGame.OwnerExclusivePlayerInfo", "RoundNumber"),
    ("/Script/ShooterGame.ZzzTailComponent", "Stripes"),
]
GROUPS = sorted(BOOKENDS + [(g, f) for g, f, _t in atc.ADDITIONS])


def rustfmt_type(field_type):
    """A braced type the way rustfmt lays it out inside an entry: one field
    per line, each with a trailing comma. A bare variant comes back as is."""
    if "{" not in field_type:
        return field_type
    head, _brace, rest = field_type.partition("{")
    fields = [part.strip() for part in rest.rstrip("} ").split(",") if part.strip()]
    inner = "".join(f"            {part},\n" for part in fields)
    return f"{head.rstrip()} {{\n{inner}        }}"


def render_table(rows, one_line=False, braced_multiline=False, handles=None):
    """A table.rs holding `rows`, each `(group, field, full FieldType)`.

    The default layout is the rustfmt'd one that is committed; `one_line` is
    the one extract_descriptors.py emits, before cargo fmt. Rows carry their
    own type because an Int32-only table cannot show a wrong-type bug -- the
    substring check it has to expose is `"Int32" in "FieldType::UInt32"`.

    `braced_multiline` lays braced types (`RepMovement { .. }`) out over
    several lines, the way the committed, rustfmt'd table.rs has them. Without
    it the formatted layout keeps them on one line, where a pass that replaces
    the one-line type literal still matches although the real file would not.

    With `handles` (`(group, handle, field)` rows, possibly none) the file is
    complete: both generated header lines and both slice lengths are written
    truthfully, and OVERLAY_HANDLE_TABLE follows the last entry as it does in
    the real file. Without it the header lines are placeholders and the file
    ends with OVERLAY_TABLE.
    """
    if one_line:
        body = "".join(
            f'    OverlayEntry {{ group_path: "{g}", field_name: "{f}", '
            f"field_type: {t} }},\n"
            for g, f, t in rows
        )
        handle_body = "".join(
            f'    OverlayHandleEntry {{ group_path: "{g}", handle: {h}, '
            f'field_name: "{f}" }},\n'
            for g, h, f in handles or ()
        )
    else:
        body = "".join(
            "    OverlayEntry {\n"
            f'        group_path: "{g}",\n'
            f'        field_name: "{f}",\n'
            f"        field_type: {rustfmt_type(t) if braced_multiline else t},\n"
            "    },\n"
            for g, f, t in rows
        )
        handle_body = "".join(
            "    OverlayHandleEntry {\n"
            f'        group_path: "{g}",\n'
            f"        handle: {h},\n"
            f'        field_name: "{f}",\n'
            "    },\n"
            for g, h, f in handles or ()
        )
    table = f"pub static OVERLAY_TABLE: [OverlayEntry; {len(rows)}] = [\n{body}];\n"
    if handles is None:
        return "// 0 entries from 0 groups.\n// Raw/Custom: 0, Skip: 0, Typed: 0.\n" + table
    raw = sum(1 for _g, _f, t in rows if t == "FieldType::Raw")
    skip = sum(1 for _g, _f, t in rows if t == "FieldType::Skip")
    return (
        "// GENERATED by tools/extract_descriptors.py -- do not edit by hand.\n"
        f"// {len(rows)} entries from {len({g for g, _f, _t in rows})} groups.\n"
        f"// Raw/Custom: {raw}, Skip: {skip}, Typed: {len(rows) - raw - skip}.\n"
        f"\n{table}\n"
        f"pub static OVERLAY_HANDLE_TABLE: [OverlayHandleEntry; {len(handles)}] = [\n"
        f"{handle_body}"
        "];\n"
    )


ADDED_KEYS = {(g, f) for g, f, _t in atc.ADDITIONS}
WITHOUT = [(g, f, "FieldType::Int32") for g, f in GROUPS if (g, f) not in ADDED_KEYS]
N_ADDED = len(atc.ADDITIONS)


class AdditionsTests(unittest.TestCase):
    def test_every_addition_names_a_real_field_type(self):
        """`FieldType::X` with a plausible X, and no duplicates.

        The COUNT is deliberately not pinned -- see 26-I and 32 for the bar an
        addition has to clear. What is pinned is that each one is well formed
        and appears once.
        """
        seen = set()
        for group, field, ftype in atc.ADDITIONS:
            # Most groups are full UE paths ("/Script/..."); a few replay-declared
            # groups are bare names ("MagazineAmmo"). Either is valid; empty or
            # non-alphanumeric-leading garbage is not.
            self.assertTrue(group.startswith("/") or group[0].isalpha(), group)
            self.assertTrue(field and not field.startswith("_"), field)
            self.assertTrue(ftype.startswith("FieldType::"), ftype)
            self.assertNotIn((group, field), seen, f"duplicate {group}/{field}")
            seen.add((group, field))

    def test_additions_stay_the_narrow_exception(self):
        """A guardrail on scope: trips on every change so growth is deliberate.

        Each entry asserts a type NO descriptor declares, so the bar is
        individual wire evidence -- the ADDITIONS rationale block plus a
        per-field Rust pin in tests/overlay.rs. The count is pinned exactly
        so adding or removing one forces this number to update in the same
        commit. The prior `<= 8` ceiling silently went stale at 13; an exact
        count cannot.

        25 -> 47 is one piece of evidence, not 22: `FTransform` reaches this
        wire as three separate double vectors, and the 22 entries apply that
        one finding to every group carrying them. `Scale3D` reading exactly
        (1,1,1) is what rules out any other split, and the replay's own
        `compatible_checksum` agrees with the grouping without having been used
        to derive it.

        47 -> 49 is two ordinary additions: `StopMovementTime`, the other half
        of a pair whose `StartMovementTime` is already Float, and
        `HandleNumber`, whose 3,741 rows hold a dense 1..765. One entry each is
        enough -- checksum propagation carries both to their sibling RPCs.

        70 -> 73 types the authoritative scoreboard counters.
        `BasicCombatStatsComponent` carries the cumulative K/D/A the game's own
        scoreboard reads from: on release-13.02 all 407 observed updates are
        exactly 32 bits, and read little-endian as Int32 the final per-player
        counters match the in-game scoreboard on all ten players, including two
        post-round objective-bomb deaths that the kill RPC stream reports but
        the scoreboard deliberately excludes.

        73 -> 86 types two time fields verified across all 714 exports. Four
        additions cover every group carrying `ServerMovementTime`; nine cover
        the descriptor-silent pawn groups carrying
        `ReplayLastTransformUpdateTimeStamp`. The other 33 timestamp groups are
        corrections from the descriptor's Skip, so they do not count here.

        64 -> 70 is two findings, not six. Five entries type `249` as the
        rotation that pairs with the already-typed `248` on every RPC that
        sends the pair numbered -- 441,814 rows, whose 3/19/35/51-bit widths
        are `3 + 16 x (flags set)` and nothing else, and whose named spelling
        the table already carries on the same UFunction. The sixth is
        `AuthCurrentRandomSeed`, 120,853 rows of near-total distinctness across
        the full i32 range.

        125 -> 127 is one finding on two twins: `EffectManagerComponent` on
        the weapons' `MulticastPlay{Continuous,OneShot}EffectFromClient`.
        Checksum 1051633025 belongs to these two parameters only; all
        3,112,054 rows over the 1,018-replay audit are IntPacked GUIDs that
        resolve to `EffectManager`, whose outer is the holder's pawn -- and
        equals the weapon's typed Instigator at that time on 3,111,803.

        127 -> 132 is the rest of `NetMulticastApplyForceModule` beside the
        already-typed HandleNumber/SourceLocation: RespawnNumber, NetTimestamp,
        ModuleType, Module, Character -- 665,519 calls each. Each checks out
        against something outside itself: RespawnNumber against the typed
        AresInventory counter, NetTimestamp against two typed clocks, Module
        by resolving to ForceModule classes, Character by equalling the row's
        own actor GUID, and ModuleType by agreeing with the Remove RPC on
        every paired row. Remove's ModuleType is not an addition: it follows
        through the checksum table, like HandleNumber does.

        132 -> 135 types `ReadyingStateComponent.AuthEquipSpeed` (3 bits on
        all 1,015,515 rows; equals its EnumByte sibling AutoEquipSpeed in the
        same packet) and the two AresInventory correction counters (32 bits,
        strictly increasing, LastSeen < Correction on every paired row, and
        every checkpoint value equal to the preceding main-stream one).

        135 -> 137 types HawkFlash's `ReplicatedMovement` (ByteComponents:
        the only reading that consumes all 1,033,952 payloads; Short fails on
        54.6%) and its `Banking` (64-bit doubles, -180..180, on 801,700 rows),
        on that exact group only.

        137 -> 142 is one finding: Cypher's trapwire and cage classes were
        renamed in 13.01, and five descriptor-typed fields -- `Deployed` on
        both wires, `CreatedByCharacter` on both ability items, the cage's
        `RelativeScale3D` -- follow them to the new paths with the same name,
        checksum and width. Relocations, like BaseTeamState, not new types.

        63 -> 64 types `LocalizedStat` as `FText`. It was removed at 62 -> 61
        for being a wrong `FString`; it is back because a decoder now exists
        and the reason given for waiting was itself wrong -- `Statistic` was
        said to carry the same fact, but it decodes to a bare integer and no
        table in this repo maps those integers to names. 225 of 225 rows now
        decode to `EnemiesBlocked`, `HealingDone` and 17 more.

        61 -> 63 types Phoenix's `MulticastAddSmokeScreenPoint`. Viper's class
        declares the same RPC and was typed; Phoenix's was not, so 2,791 rows
        over 31 replays read null while decode errors stayed at 0, and Viper's
        working side made the ability look handled. The checksum fallback could
        not carry it -- different properties, different checksums -- and
        refusing rather than guessing is what made this a missing name.

        62 -> 61 drops `LocalizedStat`: typed `FString`, it decoded to null on
        3,011 of 3,011 rows because the wire is an `FText`. Removing a type that
        produces nothing is not a loss -- the bits stay in `raw_bits`.

        56 -> 62 added the six members of `AbilityCastsThisRound[].Effects[]`,
        the authoritative debuff log. `AffectedPlayer` resolves to a manifest
        actor 224/224 over exactly 10 players.

        49 -> 56 added the seven members of `AbilityCastsThisRound`, the
        per-cast ability log. One finding, seven fields, each checked against
        something outside itself -- `Player` matches a manifest subject 352/352,
        `Round` covers exactly 0..17.

        48 -> 49 added `CalloutRegionTrackingComponent.CurrentRegion`, the named
        map area a player is standing in: every one of its 1,957 non-zero rows
        resolves through `net_guids` to a `CalloutRegion_*` path.

        49 -> 48 removed one: `MagazineAmmo.AmmoCount`. The cooked game says
        that group is an `AmmoComponent`, which the replay declares with handle
        2 as `AuthResourceAmount`, so the leaf remap in `sink/paths.rs` now
        reaches a real declaration and the guessed name is gone.
        """
        self.assertEqual(len(atc.ADDITIONS), 142, atc.ADDITIONS)

    def test_handle_additions_stay_the_narrow_exception(self):
        """Same guardrail for the handle -> name additions.

        Each names a handle the replay leaves unnamed so the overlay can type
        it; the (group, field_name) must also appear in ADDITIONS, or the name
        resolves to nothing. Pinned exactly like ADDITIONS.

        Currently empty. Its one entry named `MagazineAmmo` handle 2 as
        `AmmoCount`, which the cooked game corrected: that group is an
        `AmmoComponent`, and the replay declares handle 2 on it as
        `AuthResourceAmount`. The leaf remap in `sink/paths.rs` reaches the real
        declaration, so the hand-written name is not needed. The mechanism stays
        because the next unnamed handle will not necessarily have a native group
        to borrow from.
        """
        self.assertEqual(len(atc.HANDLE_ADDITIONS), 0, atc.HANDLE_ADDITIONS)
        addition_keys = {(g, f) for g, f, _t in atc.ADDITIONS}
        for group, _handle, field in atc.HANDLE_ADDITIONS:
            self.assertIn(
                (group, field), addition_keys,
                f"handle addition {group}/{field} has no matching ADDITION type",
            )

    def test_every_addition_is_also_verified(self):
        """An addition absent from EXPECTED would apply once and never be checked.

        The whole `FieldType::...` is asserted, not its variant name: EXPECTED
        now carries full types so `verify` can compare them exactly, and the
        variant-only form could not tell `FieldType::Int32` from
        `FieldType::UInt32`.
        """
        for group, field, ftype in atc.ADDITIONS:
            self.assertIn((group, field, ftype), atc.EXPECTED)

    def _assert_inserted_in_order(self, content):
        keys = [(g, f) for g, f, _ in atc.parse_entries(content)]
        self.assertEqual(keys, sorted(keys), "table must stay sorted")
        for group, field, _ in atc.ADDITIONS:
            self.assertIn((group, field), keys)
        self.assertEqual(len(keys), len(WITHOUT) + N_ADDED)
        return keys

    def test_inserts_into_the_formatted_layout(self):
        out, n = atc.apply_additions(render_table(WITHOUT))
        self.assertEqual(n, N_ADDED)
        self._assert_inserted_in_order(out)

    def test_inserts_into_the_freshly_generated_one_line_layout(self):
        """The layout the script actually meets when run in documented order."""
        out, n = atc.apply_additions(render_table(WITHOUT, one_line=True))
        self.assertEqual(n, N_ADDED)
        self._assert_inserted_in_order(out)

    def test_is_idempotent(self):
        once, n1 = atc.apply_additions(render_table(WITHOUT))
        twice, n2 = atc.apply_additions(once)
        self.assertEqual((n1, n2), (N_ADDED, 0))
        self.assertEqual(once, twice)

    def test_verify_reports_a_missing_addition(self):
        problems = atc.verify(render_table(WITHOUT))
        self.assertTrue(
            any("LoadoutValue" in p and "BaseTeamState" in p for p in problems),
            problems,
        )

    def test_verify_passes_once_added(self):
        out, _ = atc.apply_additions(render_table(WITHOUT))
        remaining = [p for p in atc.verify(out) if "BaseTeamState" in p]
        self.assertEqual(remaining, [])

    def test_declared_length_is_resynced(self):
        out, _ = atc.apply_additions(render_table(WITHOUT))
        out = atc.resync_table_len(out)
        self.assertIn(
            f"[OverlayEntry; {len(WITHOUT) + len(atc.ADDITIONS)}]", out
        )

    def test_both_generated_header_lines_are_recounted(self):
        """The shape line went stale for exactly the reason the bucket line did.

        `// N entries from M groups.` is written by extract_descriptors.py from
        the descriptors it read, and ADDITIONS then inserts entries -- and, when
        an addition names a group no descriptor declared, a whole new group. The
        committed table said "1185 entries from 171 groups" above a bucket line
        that summed to 1188, over a slice declared 1188 long.
        """
        out, _ = atc.apply_additions(render_table(WITHOUT))
        out, lines = atc.rewrite_header(out)
        n_groups = len({g for g, _f in GROUPS})
        self.assertEqual(lines[0],
                         f"// {len(GROUPS)} entries from {n_groups} groups.")
        self.assertIn(lines[0], out)
        # The two lines must agree with each other and with the slice length.
        buckets = [int(n) for n in re.findall(r": (\d+)", lines[1])]
        self.assertEqual(sum(buckets), len(GROUPS))
        self.assertIn(f"[OverlayEntry; {len(GROUPS)}]",
                      atc.resync_table_len(out))

    def test_rewriting_the_header_is_idempotent(self):
        out, _ = atc.apply_additions(render_table(WITHOUT))
        once, lines1 = atc.rewrite_header(out)
        twice, lines2 = atc.rewrite_header(once)
        self.assertEqual((once, lines1), (twice, lines2))

    def test_a_missing_header_line_is_a_hard_failure(self):
        """Not a silent skip: a table without the line was not generated by
        extract_descriptors.py, and recounting it would say nothing."""
        out, _ = atc.apply_additions(render_table(WITHOUT))
        with self.assertRaises(SystemExit):
            atc.rewrite_header(out.replace("// 0 entries from 0 groups.\n", ""))

    def test_appends_past_the_end_of_the_slice(self):
        """An entry sorting after every existing entry is the new tail, not a
        fatal error.

        The first `];` in the final split block is OVERLAY_TABLE's close; the
        splice lands before it and the table stays sorted. The prior behavior
        was to refuse -- that blocked any addition whose group sorts last
        (e.g. ZoomMultiplierComponent, which is how the append path was
        forced into existence), so the append is handled now rather than
        rejected. The end-to-end insertion tests above also cross this path
        because the ZoomMultiplier additions sort past the synthetic tail
        bookend.
        """
        earlier = [("/AAAAA.First", "Field", "FieldType::Int32")]
        out, n = atc.apply_additions(render_table(earlier))
        self.assertEqual(n, len(atc.ADDITIONS))
        keys = [(g, f) for g, f, _ in atc.parse_entries(out)]
        self.assertEqual(keys, sorted(keys), "table must stay sorted after append")
        self.assertEqual(len(keys), 1 + len(atc.ADDITIONS))
        # OVERLAY_TABLE's closing bracket is still present exactly once.
        self.assertEqual(out.count("];\n"), 1)


class RetypeTests(unittest.TestCase):
    """`retype` keys on each block's OWN entry, never on text elsewhere.

    The split on `    OverlayEntry {` leaves OVERLAY_HANDLE_TABLE in the last
    block, and that table repeats group paths and field names. A substring pass
    would read them as the last entry's; these pin that it does not.
    """

    GROUP = "/Script/ShooterGame.ReplayEffectComponent:ReplayPlayContinuousEffectAtLocation"

    def table(self, last_type):
        return render_table([
            (self.GROUP, "AllianceFilter", "FieldType::EnumRemainingBits"),
            (self.GROUP, "AllianceFilterX", "FieldType::EnumRemainingBits"),
            ("/Script/ShooterGame.ZzzTailComponent", "Stripes", last_type),
        ], handles=[(self.GROUP, 28, "AllianceFilter")])

    def test_only_the_exact_entry_changes(self):
        # The tail entry carries the old type too, and the handle table after
        # it names the same group and field -- the shape a substring pass
        # would misread as "the last entry is AllianceFilter".
        source = self.table("FieldType::EnumRemainingBits")
        out, n = atc.retype(source, atc.exact_retype(
            self.GROUP, "AllianceFilter",
            "FieldType::EnumRemainingBits", "FieldType::EnumByte"))
        self.assertEqual(n, 1)
        self.assertEqual(
            [(f, t) for _g, f, t in atc.parse_entries(out)],
            [("AllianceFilter", "FieldType::EnumByte"),
             ("AllianceFilterX", "FieldType::EnumRemainingBits"),
             ("Stripes", "FieldType::EnumRemainingBits")])

    def test_an_already_corrected_table_changes_nothing(self):
        out, n = atc.retype(self.table("FieldType::Float"), atc.exact_retype(
            self.GROUP, "AllianceFilter", "FieldType::EnumByte", "FieldType::Raw"))
        self.assertEqual(n, 0)
        self.assertEqual(out, self.table("FieldType::Float"))

    def test_an_unexpected_count_is_a_hard_failure(self):
        with self.assertRaises(SystemExit):
            atc.retype(self.table("FieldType::Float"), atc.exact_retype(
                self.GROUP, "AllianceFilter",
                "FieldType::EnumRemainingBits", "FieldType::EnumByte", expected=2))

    def test_a_braced_retype_changes_the_entry_it_counts(self):
        """The count claims an entry changed. rustfmt breaks a braced type
        over lines, so its one-line literal is not in the file: replacing that
        literal changed nothing while the count still said one entry had. A
        change the rewrite cannot make in place is refused, not guessed."""
        group = atc.GAME_OBJECT_BYTE_ROTATOR_GROUPS[0]
        rep = ("FieldType::RepMovement {{ rotation: RotatorQuantization::{}, "
               "location: VectorQuantization::{} }}")
        short_whole = rep.format("ShortComponents", "RoundWholeNumber")
        byte_whole = rep.format("ByteComponents", "RoundWholeNumber")
        for one_line in (True, False):
            with self.subTest(one_line=one_line):
                source = whole_table(UNCORRECTED_GAME_OBJECT_ROTATORS,
                                     one_line=one_line, braced_multiline=not one_line)
                out, n = atc.retype(source, atc.exact_retype(
                    group, "ReplicatedMovement", short_whole, byte_whole))
                types = {(g, f): t for g, f, t in atc.parse_entries(out)}
                self.assertEqual((n, types[(group, "ReplicatedMovement")]),
                                 (1, byte_whole))
                with self.assertRaises(SystemExit):
                    atc.retype(source, atc.exact_retype(
                        group, "ReplicatedMovement", short_whole,
                        rep.format("ByteComponents", "RoundTwoDecimals")))


#: A weapon group of the shape the "215"/"216" pass discovers for itself.
WEAPON_GROUP = "/Game/Equippables/Guns/Rifles/Vandal.Vandal_C"
WEAPON_ROWS = [
    (WEAPON_GROUP, "215", "FieldType::EnumRemainingBits"),
    (WEAPON_GROUP, "216", "FieldType::EnumRemainingBits"),
]


def whole_table(overrides=None, drop=(), one_line=False, braced_multiline=False,
                extra=(), handles=()):
    """A complete table.rs that satisfies every correction, minus `overrides`.

    Derived from EXPECTED rather than hand-written, so it cannot go stale as
    corrections are added. `overrides` maps an EXPECTED key to the type the
    file should carry INSTEAD, which is how "regenerated but never corrected"
    is expressed, and `drop` leaves keys out. The two generated header lines
    and both slice lengths are written truthfully, so `main()` fails for the
    reason under test and not because the fixture is malformed.

    `extra` adds `(group, field, type)` rows and `handles` fills
    OVERLAY_HANDLE_TABLE with `(group, handle, field)` entries, the text the
    real file carries after its last OverlayEntry.
    """
    overrides = overrides or {}
    rows = [
        (g, f, overrides.get((g, f), t))
        for g, f, t in list(atc.EXPECTED) + WEAPON_ROWS
        if (g, f) not in drop
    ] + list(extra)
    return render_table(sorted(rows), one_line, braced_multiline, list(handles))


#: The two mutations below are deliberately BUCKET-NEUTRAL -- they swap one
#: typed variant for another, so the generated header lines are identical
#: either way and `--check` cannot pass or fail for header reasons.
#:
#: `SmokeScreen.ReplicatedMovement` is rewritten per entry, so it applies in
#: BOTH layouts: a file carrying ShortComponents is correctable.
UNCORRECTED_SMOKESCREEN = {
    ("SmokeScreen", "ReplicatedMovement"):
        "FieldType::RepMovement { rotation: RotatorQuantization::ShortComponents, "
        "location: VectorQuantization::RoundWholeNumber }",
}
#: Gekko's Wingman as the generator emits it: whole units, the default every
#: `RepMovement` entry starts from.
UNCORRECTED_SEEKER_NADE = {
    (atc.SEEKER_NADE_GROUP, "ReplicatedMovement"):
        "FieldType::RepMovement { rotation: RotatorQuantization::ShortComponents, "
        "location: VectorQuantization::RoundWholeNumber }",
}
#: The five AGameObject smoke/zone classes as the generator emits them: the
#: bare `.ReplicatedMovement()` builder default, short rotator components.
UNCORRECTED_GAME_OBJECT_ROTATORS = {
    (group, "ReplicatedMovement"):
        "FieldType::RepMovement { rotation: RotatorQuantization::ShortComponents, "
        "location: VectorQuantization::RoundWholeNumber }"
    for group in atc.GAME_OBJECT_BYTE_ROTATOR_GROUPS
}
#: A correction whose entry is gone, as if the descriptors stopped declaring
#: it: no pass can create the entry, so the correction is DEAD in either
#: layout and has to fail loudly. Pass it as `drop=`.
DEAD_TIME_REMAINING = [("TimedBomb.TimedBomb_C", "TimeRemainingToExplode")]
#: The first line of each FAILED section `main()` prints.
DEAD_HEADER = "corrections are missing from"
UNCORRECTED_HEADER = "the file was never corrected"


class MainOnDiskTests(unittest.TestCase):
    """`--check` verified the CORRECTED COPY, not the file on disk.

    It applied every correction to the in-memory content and then verified
    that, suppressing only the write. So it could not tell "table.rs is already
    corrected" from "table.rs is correctable and nobody corrected it" -- and CI
    runs exactly this command, so a regenerated table.rs committed without
    running the script goes green while the Rust build uses the uncorrected one.
    """

    def setUp(self):
        self._real_table = atc.TABLE_RS
        self._temp = tempfile.TemporaryDirectory()
        self.path = Path(self._temp.name) / "table.rs"
        atc.TABLE_RS = self.path
        self._real_argv = sys.argv

    def tearDown(self):
        atc.TABLE_RS = self._real_table
        sys.argv = self._real_argv
        self._temp.cleanup()

    def run_main(self, source, *args):
        """`(exit_code, stdout, stderr)` for one main() run over `source`."""
        self.path.write_text(source, encoding="utf-8")
        sys.argv = ["apply_type_corrections.py", *args]
        out, err = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
            code = atc.main()
        return code, out.getvalue(), err.getvalue()

    def test_a_correct_table_still_passes(self):
        code, out, err = self.run_main(whole_table(), "--check")
        self.assertEqual(code, 0, err)
        self.assertIn("verified", out)

    def test_a_correctable_but_uncorrected_file_fails(self):
        """The whole point. The passes CAN fix it, and nobody ran them."""
        code, _out, err = self.run_main(
            whole_table(UNCORRECTED_SMOKESCREEN), "--check"
        )
        self.assertEqual(code, 1, "--check must not pass an uncorrected file")
        self.assertIn("ShortComponents", err)

    def test_a_dead_pattern_still_fails_loudly(self):
        """Unchanged behaviour: a correction that cannot be applied at all."""
        code, _out, err = self.run_main(
            whole_table(drop=DEAD_TIME_REMAINING), "--check"
        )
        self.assertEqual(code, 1)
        self.assertIn("TimeRemainingToExplode", err)
        self.assertIn(DEAD_HEADER, err)

    def test_the_two_failure_modes_are_distinguishable(self):
        """One table can trip BOTH at once -- a correction whose entry is gone
        and one the passes apply fine in memory. One report that hides the
        other is how the second one gets missed."""
        code, _out, err = self.run_main(
            whole_table(UNCORRECTED_SMOKESCREEN, drop=DEAD_TIME_REMAINING), "--check")
        self.assertEqual(code, 1)
        self.assertIn("TimeRemainingToExplode", err)
        self.assertIn("ShortComponents", err)
        self.assertIn(DEAD_HEADER, err)
        self.assertIn(UNCORRECTED_HEADER, err)

    def test_check_writes_nothing(self):
        source = whole_table(UNCORRECTED_SMOKESCREEN)
        self.run_main(source, "--check")
        self.assertEqual(self.path.read_text(encoding="utf-8"), source)

    def test_unknown_flag_is_rejected_and_cannot_fall_into_write_mode(self):
        source = whole_table(UNCORRECTED_SMOKESCREEN)
        self.path.write_text(source, encoding="utf-8")
        sys.argv = ["apply_type_corrections.py", "--chekc"]
        with contextlib.redirect_stdout(io.StringIO()), \
                contextlib.redirect_stderr(io.StringIO()):
            with self.assertRaises(SystemExit) as raised:
                atc.main()
        self.assertEqual(raised.exception.code, 2)
        self.assertEqual(self.path.read_text(encoding="utf-8"), source)

    def test_final_verification_failure_leaves_the_file_byte_identical(self):
        """A partially correctable run must not publish before verify passes."""
        source = whole_table(UNCORRECTED_SMOKESCREEN, drop=DEAD_TIME_REMAINING)
        code, _out, _err = self.run_main(source)
        self.assertEqual(code, 1)
        self.assertEqual(self.path.read_text(encoding="utf-8"), source)

    def test_applying_then_checking_passes(self):
        """The documented cure: run without --check, and --check goes green."""
        code, _out, err = self.run_main(whole_table(UNCORRECTED_SMOKESCREEN))
        self.assertEqual(code, 0, err)
        sys.argv = ["apply_type_corrections.py", "--check"]
        with contextlib.redirect_stdout(io.StringIO()), \
                contextlib.redirect_stderr(io.StringIO()):
            self.assertEqual(atc.main(), 0)

    def test_the_seeker_nade_location_level_is_corrected_in_both_layouts(self):
        """The one two-decimal class. The pass that pins it must fire on the
        generator's one-line output AND on the rustfmt'd file, and `--check`
        must refuse a file that still carries the whole-unit default."""
        want = (
            "FieldType::RepMovement { rotation: RotatorQuantization::ShortComponents, "
            "location: VectorQuantization::RoundTwoDecimals }"
        )
        for one_line in (True, False):
            with self.subTest(one_line=one_line):
                source = whole_table(UNCORRECTED_SEEKER_NADE, one_line=one_line)
                code, _out, err = self.run_main(source, "--check")
                self.assertEqual(code, 1, "--check must not pass the default")
                self.assertIn("RoundWholeNumber", err)
                code, _out, err = self.run_main(source)
                self.assertEqual(code, 0, err)
                types = {
                    (g, f): t for g, f, t in
                    atc.parse_entries(self.path.read_text(encoding="utf-8"))
                }
                self.assertEqual(
                    types[(atc.SEEKER_NADE_GROUP, "ReplicatedMovement")], want)

    def test_the_game_object_rotators_are_corrected_in_both_layouts(self):
        """The five AGameObject classes read byte rotator components.

        The pass has to fire on the generator's one-line output and on the
        rustfmt'd file -- a `str.replace` of the one-line type literal would
        match the first and silently not the second -- and `--check` must
        refuse a file that still carries the short default on any of them.
        """
        want = (
            "FieldType::RepMovement { rotation: RotatorQuantization::ByteComponents, "
            "location: VectorQuantization::RoundWholeNumber }"
        )
        self.assertEqual(len(atc.GAME_OBJECT_BYTE_ROTATOR_GROUPS), 5)
        for one_line in (True, False):
            with self.subTest(one_line=one_line):
                source = whole_table(UNCORRECTED_GAME_OBJECT_ROTATORS,
                                     one_line=one_line, braced_multiline=not one_line)
                if not one_line:
                    self.assertIn(
                        "            rotation: RotatorQuantization::ShortComponents,\n",
                        source, "the fixture must carry rustfmt's multi-line form")
                code, _out, err = self.run_main(source, "--check")
                self.assertEqual(code, 1, "--check must not pass the short default")
                for group in atc.GAME_OBJECT_BYTE_ROTATOR_GROUPS:
                    self.assertIn(group, err)
                code, _out, err = self.run_main(source)
                self.assertEqual(code, 0, err)
                types = {
                    (g, f): t for g, f, t in
                    atc.parse_entries(self.path.read_text(encoding="utf-8"))
                }
                for group in atc.GAME_OBJECT_BYTE_ROTATOR_GROUPS:
                    self.assertEqual(types[(group, "ReplicatedMovement")], want, group)
                # The one short-rotator class the table keeps is untouched.
                self.assertIn(
                    "ShortComponents",
                    types[(atc.SEEKER_NADE_GROUP, "ReplicatedMovement")])

    def test_a_partially_corrected_rotator_set_is_a_hard_failure(self):
        """Two of five still short is neither "fresh" nor "done": refuse it."""
        groups = atc.GAME_OBJECT_BYTE_ROTATOR_GROUPS
        partial = {k: v for k, v in UNCORRECTED_GAME_OBJECT_ROTATORS.items()
                   if k[0] in groups[:2]}
        with self.assertRaises(SystemExit):
            atc.retype(whole_table(partial), atc.GAME_OBJECT_ROTATOR_RETYPE)
        out, n = atc.retype(whole_table(), atc.GAME_OBJECT_ROTATOR_RETYPE)
        self.assertEqual(n, 0, "an already corrected table must change nothing")
        self.assertEqual(out, whole_table())

    def test_an_uncorrected_weapon_group_is_reported(self):
        """The 18 weapon groups had NO expectation of any kind.

        EXPECTED's "215"/"216" rows name five hardcoded non-weapon groups; the
        weapon pass discovers its own targets and nothing checked its result,
        so it could no-op in silence.
        """
        raw_weapons = {(WEAPON_GROUP, "215"): "FieldType::Raw"}
        code, _out, err = self.run_main(whole_table(raw_weapons), "--check")
        self.assertEqual(code, 1, "an uncorrected weapon group must be caught")
        self.assertIn(WEAPON_GROUP, err)

    def test_a_table_with_no_weapon_groups_at_all_is_reported(self):
        """The other shape of the same silence: the discovery finds nothing.

        `content.splitlines()` is how the pass finds its groups. If that ever
        stops matching, or the groups stop being emitted, "Applied 0" is the
        only trace -- so the absence itself has to be the failure.
        """
        code, _out, err = self.run_main(
            whole_table(drop=[(WEAPON_GROUP, "215"), (WEAPON_GROUP, "216")]),
            "--check",
        )
        self.assertEqual(code, 1)
        self.assertIn("/Game/Equippables/", err)

    def test_the_summary_counts_the_weapon_expectations_too(self):
        """The summary line is a claim about how much was checked."""
        _code, out, _err = self.run_main(whole_table(), "--check")
        self.assertIn(f"all {len(atc.EXPECTED) + len(WEAPON_ROWS)} ", out)

    def test_the_handle_table_cannot_retype_the_last_entry(self):
        """Splitting on `    OverlayEntry {` leaves OVERLAY_HANDLE_TABLE inside
        the last block, and handle entries repeat group paths and field names.
        A pass that looks for its trigger anywhere in the block reads a handle
        entry as the last entry's own group or field and retypes that entry.
        Nothing reports it: verify() checks EXPECTED keys only, and the exit
        code is 0. One case per trigger a pass has used; each tail type is the
        type that pass rewrites."""
        tail = ("zzz/Tail.Tail_C", "Unrelated")
        short_whole = (
            "FieldType::RepMovement { rotation: RotatorQuantization::ShortComponents, "
            "location: VectorQuantization::RoundWholeNumber }"
        )
        damage = "/Script/ShooterGame.DamageableComponent:MulticastNotifyDamage_"
        cases = [
            ("FieldType::Raw", damage + "Base", "EquippableUsed"),
            ("FieldType::Raw", damage + "Point", "DamageOrigin"),
            ("FieldType::Skip", "/Game/Characters/X/Pawn_X.Pawn_X_C",
             "ReplayLastTransformUpdateTimeStamp"),
            (short_whole, "/Game/Characters/X/Projectile_X_SmokeScreen."
             "Projectile_X_SmokeScreen_C", "ReplicatedMovement"),
            (short_whole, atc.SEEKER_NADE_GROUP, "ReplicatedMovement"),
            ("FieldType::Raw", "/Script/ShooterGame.EquippableStateMachineComponent",
             "TransitionContext"),
        ]
        for tail_type, handle_group, handle_field in cases:
            for one_line in (True, False):
                with self.subTest(field=handle_field, group=handle_group,
                                  one_line=one_line):
                    source = whole_table(
                        extra=[(*tail, tail_type)],
                        handles=[(handle_group, 7, handle_field)],
                        one_line=one_line, braced_multiline=not one_line)
                    # The fixture must put the handle table after the tail
                    # row, or this passes without testing anything.
                    self.assertEqual(
                        [(g, f) for g, f, _t in atc.parse_entries(source)][-1], tail)
                    self.assertIn(
                        f'field_name: "{handle_field}"',
                        source.partition("OVERLAY_HANDLE_TABLE")[2])
                    code, _out, err = self.run_main(source)
                    self.assertEqual(code, 0, err)
                    types = {
                        (g, f): t for g, f, t in
                        atc.parse_entries(self.path.read_text(encoding="utf-8"))
                    }
                    self.assertEqual(types[tail], atc.normalize_type(tail_type))


class VerifyMatchesTheWholeTypeTests(unittest.TestCase):
    """`verify` compared the required type as a SUBSTRING of the found one.

    `"Int32" in "FieldType::UInt32"` is True and `"Byte" in "FieldType::EnumByte"`
    is True, so an entry with the wrong signedness or the wrong byte variant
    verified clean -- the two mistakes a hand-written type table is most likely
    to make were the two it could not catch.
    """

    def _wrong_type(self, group, field, wrong):
        """One-entry table declaring a real EXPECTED key at the wrong type."""
        return render_table([(group, field, wrong)])

    @staticmethod
    def _about(problems, field):
        """Only the problems naming `field` -- the rest of EXPECTED is absent
        from a one-entry table and would drown the assertion message."""
        return [p for p in problems if field in p]

    def test_a_wrong_signedness_is_reported(self):
        table = self._wrong_type(
            "/Script/ShooterGame.BaseTeamState", "LoadoutValue", "FieldType::UInt32"
        )
        about = self._about(atc.verify(table), "LoadoutValue")
        self.assertTrue(
            any("UInt32" in p for p in about),
            f"UInt32 where Int32 is required must be reported; got {about}",
        )

    def test_a_wrong_byte_variant_is_reported(self):
        group = ("/Game/Characters/_Core/Comp_AbilityStatisticsReplicator"
                 ".Comp_AbilityStatisticsReplicator_C")
        field = "Slot_12_22D571914FAFD5F0EBD400B7E2F28B36"
        about = self._about(
            atc.verify(self._wrong_type(group, field, "FieldType::EnumByte")), field
        )
        self.assertTrue(
            any("EnumByte" in p for p in about),
            f"EnumByte where Byte is required must be reported; got {about}",
        )

    def test_a_pre_existing_wrong_type_is_skipped_by_additions_and_reported(self):
        """The other half: ADDITIONS skips a key that is already there.

        So a table that already carries the key at the WRONG type is neither
        corrected nor -- before this -- reported. Skipping is the right call
        (silently overwriting a declaration the descriptors do make would be
        worse), which is exactly why the report has to fire.
        """
        table = self._wrong_type(
            "/Script/ShooterGame.BaseTeamState", "LoadoutValue", "FieldType::UInt32"
        )
        out, added = atc.apply_additions(table)
        self.assertEqual(added, len(atc.ADDITIONS) - 1, "the present key is skipped")
        about = self._about(atc.verify(out), "LoadoutValue")
        self.assertTrue(
            about, "the skipped, wrong-typed key must be reported; nothing was"
        )

    def test_the_committed_types_still_verify(self):
        """The tightening must not turn the real table's types into failures."""
        problems = atc.verify(atc.TABLE_RS.read_text(encoding="utf-8"))
        self.assertEqual(problems, [])


if __name__ == "__main__":
    unittest.main()
