//! Type-aware field decoders for Unreal Engine replay primitives.
//!
//! # Purpose
//!
//! The replay pipeline records every field update as raw bits. This crate
//! converts those bits into typed values by applying the same decoding logic
//! that the game client uses (ported from the C# reference parser).
//!
//! # Design: additive overlay
//!
//! Decoding is *additive*: raw bits are always preserved. A successful decode
//! populates one of the `value_*` slots; a failure leaves them all `None` and
//! increments an error counter. This guarantees forward compatibility: unknown
//! fields or layout changes never lose data, they just lack typed overlays
//! until the decoder is updated. Nothing here ever substitutes a plausible
//! value for one it could not read.
//!
//! # Supported types
//!
//! | Type | Bits consumed | Value slot |
//! |------|---------------|------------|
//! | Bool | 1 | `value_bool` |
//! | Byte | 8 | `value_i64` |
//! | EnumByte | 8 | `value_i64` |
//! | Int32 | 32 | `value_i64` |
//! | UInt32 | 32 | `value_i64` |
//! | Int64 | 64 | `value_i64` |
//! | UInt64 | 64 | `value_i64` (refused past `i64::MAX`) |
//! | Float | 32 | `value_f64` |
//! | Double | 64 | `value_f64` |
//! | FString | variable | `value_str` |
//! | FText | variable | `value_str` |
//! | FName | variable | `value_str` |
//! | ObjectNetGuid | variable (IntPacked) | `value_i64` |
//! | Guid | 128 | `value_str` (hex) |
//! | SerializedInt(max) | variable | `value_i64` |
//! | EnumRemainingBits | all remaining | `value_i64` |
//! | GameplayTag | variable (IntPacked) | `value_i64` (tag index) |
//! | ByteArray(max) | variable | `value_str` (hex) |
//! | FVector(double) | 192 | `value_str` (compact) |
//! | FVector(float) | 96 | `value_str` (compact) |
//! | VectorNetQuantize(1/10/100) | variable | `value_str` (compact) |
//! | VectorNetQuantizeNormal | ~48 (3 x 16 serialized) | `value_str` (compact) |
//! | RotationShort | 3 x (1+16) max | `value_str` (compact) |
//! | RotationByte | 3 x (1+8) max | `value_str` (compact) |
//! | Transform | 4 x 32 + 3 x 32 + 3 x 32 = 320 | `value_str` (compact) |
//! | RepMovement | variable | `value_str` (JSON object, 8 members) |
//! | RepLayoutDynamicArray | variable | flattened child rows plus raw parent |
//!
//! Three decoders sit outside that table because they key off the field's name
//! or array shape rather than a scalar declared type: [`decode_struct_array`]
//! for RepLayout arrays, [`structs`] for named struct blobs, and [`effect`] for
//! the `EffectContainer` arrays, which fill `value_str` with a JSON array. All
//! are additive in the same sense -- the parent raw bits survive.
//!
//! # Module map
//!
//! | Module | What it owns |
//! |--------|--------------|
//! | `types` | The model structs and their `Display` forms |
//! | `decode` | `FieldType`, `DecodedValue` and the dispatch; `scalar` and `geometry` hold the readers |
//! | `overlay` | The `(group_path, field_name)` table, its hash index and the resolution order |
//! | `table` | GENERATED by `tools/extract_descriptors.py` -- never hand-edited |
//! | `array` | The RepLayout dynamic-array walker and the nesting schema |
//! | `structs` | The three named struct blobs, one module each |
//! | `effect` | The `EffectContainer` arrays: framing, elements, JSON |
//!
//! # Feature flags
//!
//! [`decode_field`] and the exported model types are the crate's core and are
//! always compiled: everything else is expressed in terms of them, so there is
//! no flag for them. The four decoders layered on top are independent of each
//! other and each can be left out:
//!
//! | Feature | Brings in | Notes |
//! |---------|-----------|-------|
//! | `overlay` | [`OverlayTable`], [`apply_overlay_with_handle`], `OVERLAY_TABLE` | Also compiles the generated table |
//! | `array` | [`decode_struct_array`] and [`COMBAT_ROUNDS_SCHEMA`] | |
//! | `structs` | [`structs`] | |
//! | `effect` | [`effect`] | |
//!
//! All four are on by default, so a consumer that does nothing gets the whole
//! crate. `overlay` is the one worth dropping if the primitive decoders are all
//! you want: it is what pulls in the generated table.

#![forbid(unsafe_code)]

mod decode;
mod ftext;
mod types;

pub mod cnc;

/// Numeric FastArray headers, item IDs and raw property windows.
///
/// No in-tree caller: the export path preserves these windows as raw bits and
/// `tools/extract_fastarray_observations.py` does the extraction independently
/// in Python. This is the Rust reading of the same grammar, published for
/// consumers and kept in step with that tool; see
/// docs/GAS_AND_PATCHVOLUME_INVESTIGATION.md.
pub mod fastarray;

#[cfg(feature = "array")]
mod array;
#[cfg(feature = "overlay")]
mod checksum_table;
/// Effect-blob decoder for the `EffectContainer` arrays that RPCs carry as
/// `FloatValues` / `ObjectValues` / `VectorValues`. Wired into the export path
/// through [`effect::decode_effect_blob_json`]; one RPC is deliberately left to
/// the Python port in `tools/to_valplay_bundle.py`. See the module docs.
#[cfg(feature = "effect")]
pub mod effect;
#[cfg(feature = "overlay")]
mod overlay;
#[cfg(feature = "overlay")]
mod scoped_types;
#[cfg(feature = "structs")]
pub mod structs;
#[cfg(feature = "overlay")]
mod table;
#[cfg(test)]
mod tests;

pub use decode::{DecodeError, DecodedValue, FieldType, decode_field};
pub use ftext::{
    FTextArgument, FTextArgumentValue, FTextName, FTextNumberFormat, FTextTree, FTextTreeError,
    decode_ftext_tree,
};
pub use types::{
    FQuat, FRepMovement, FRotator, FTransform, FVector, RotatorQuantization, VectorQuantization,
};

#[cfg(feature = "array")]
pub use array::{
    ABILITY_CASTS_SCHEMA, ABILITY_EFFECTS_SCHEMA, ArrayDecodeStats, ArrayFieldSchema,
    COMBAT_ROUNDS_SCHEMA, FlattenedField, LIFE_CHANGE_BY_SECTION_SCHEMA, LIFE_CHANGE_DAMAGE_SCHEMA,
    LIFE_CHANGE_SECTION_SCHEMA, MAX_ELEMENTS, MAX_FIELDS_PER_ELEMENT, MAX_RECURSION_DEPTH,
    decode_object_ref_array, decode_object_ref_array_with_stats, decode_struct_array,
    decode_struct_array_exact,
};
#[cfg(feature = "overlay")]
pub use checksum_table::CHECKSUM_TYPES;
#[cfg(feature = "effect")]
pub use effect::{EffectArrayKind, EffectBlobError, decode_effect_blob_json};
#[cfg(feature = "overlay")]
pub use overlay::{
    DecodeErrorKind, GroupHashState, OverlayEntry, OverlayErrorReport, OverlayErrorRow,
    OverlayHandleEntry, OverlayStats, OverlayTable, apply_overlay, apply_overlay_with_checksum,
    apply_overlay_with_handle, canonical_group, group_hash_state, lookup_checksum,
    resolve_field_type, resolve_field_type_with_checksum,
};
#[cfg(feature = "overlay")]
pub use table::{OVERLAY_HANDLE_TABLE, OVERLAY_TABLE};

/// The encoder side of the bit formats `vrf_bitio::BitReader` reads, for every
/// module's tests: values go in least significant bit first, the order the
/// reader takes them out.
#[cfg(test)]
pub(crate) mod test_bits {
    /// A bit string under construction.
    #[derive(Debug, Default)]
    pub(crate) struct BitWriter(pub(crate) Vec<bool>);

    impl BitWriter {
        pub(crate) fn new() -> Self {
            Self::default()
        }

        /// The low `width` (at most 64) bits of `value`.
        pub(crate) fn bits(&mut self, value: u64, width: u32) -> &mut Self {
            self.0.extend((0..width).map(|i| (value >> i) & 1 != 0));
            self
        }

        /// `count` copies of `bit`.
        pub(crate) fn repeat(&mut self, bit: bool, count: usize) -> &mut Self {
            self.0.extend(std::iter::repeat_n(bit, count));
            self
        }

        /// Unreal's `SerializeIntPacked`: seven value bits per byte, above a
        /// continuation bit that is set while more bytes follow.
        pub(crate) fn int_packed(&mut self, mut value: u32) -> &mut Self {
            loop {
                let more = value > 0x7f;
                self.bits(u64::from(((value & 0x7f) << 1) | u32::from(more)), 8);
                value >>= 7;
                if !more {
                    return self;
                }
            }
        }

        /// Unreal's `SerializeInt(value, max)`: only the bits that could still
        /// raise the value without reaching `max`.
        pub(crate) fn serialized_int(&mut self, value: u32, max: u32) -> &mut Self {
            let (mut written, mut mask) = (0u32, 1u32);
            while written.saturating_add(mask) < max {
                let bit = value & mask != 0;
                self.0.push(bit);
                if bit {
                    written |= mask;
                }
                mask <<= 1;
            }
            self
        }

        pub(crate) fn i32(&mut self, value: i32) -> &mut Self {
            self.bits(u64::from(value as u32), 32)
        }

        /// Another writer's bits, after these.
        pub(crate) fn append(&mut self, other: &Self) -> &mut Self {
            self.0.extend_from_slice(&other.0);
            self
        }

        pub(crate) fn bit_len(&self) -> u32 {
            self.0.len() as u32
        }

        /// The bytes, zero-padded to a whole byte, and the exact bit count.
        pub(crate) fn finish(&self) -> (Vec<u8>, u32) {
            let mut bytes = vec![0u8; self.0.len().div_ceil(8)];
            for (i, _) in self.0.iter().enumerate().filter(|(_, bit)| **bit) {
                bytes[i / 8] |= 1 << (i % 8);
            }
            (bytes, self.bit_len())
        }
    }

    /// Bytes from hex digits; whitespace between them is ignored.
    pub(crate) fn hex(digits: &str) -> Vec<u8> {
        let clean: Vec<u8> = digits
            .bytes()
            .filter(|b| !b.is_ascii_whitespace())
            .collect();
        assert!(
            clean.len() % 2 == 0,
            "odd number of hex digits in {digits:?}"
        );
        clean
            .chunks(2)
            .map(|pair| u8::from_str_radix(std::str::from_utf8(pair).unwrap(), 16).unwrap())
            .collect()
    }
}
