#!/usr/bin/env python3
"""Generate `crates/vrf-decode/src/checksum_table.rs` from export manifests.

Unreal hashes a property's type into each field's `compatible_checksum`, so the
checksum is a content address, stable across builds (`Scale3D` is 2983776962 on
every build checked). A field the overlay table does not type takes the type of
a typed field sharing its checksum: this records `checksum -> FieldType` for
every `(group_path, field_name)` the table types.

A checksum whose donors disagree is dropped (on the 1,018-replay corpus only
`ReplicatedMovement`, Byte vs Short rotators); a committed entry they now make
unsafe fails `--check` and is omitted on write. A committed type changes only
through `--retype CHECKSUM`, refused unless the committed and learned types
disagree, and in `--check`.

Usage:
    python tools/extract_checksum_types.py --export out/probe [--export out/other]
    python tools/extract_checksum_types.py --export out/probe --check
    python tools/extract_checksum_types.py --export out/probe --retype 1129645208
"""

from __future__ import annotations

import argparse
import collections
import dataclasses
import json
import re
import sys
from pathlib import Path

import overlay_mirror
from atomic_io import atomic_write_text

REPO = Path(__file__).resolve().parents[1]
TABLE_RS = REPO / "crates" / "vrf-decode" / "src" / "table.rs"
OUT_RS = REPO / "crates" / "vrf-decode" / "src" / "checksum_table.rs"

#: Types that carry no decode, so they teach nothing. Compared whole: a
#: substring test would also drop a type whose name merely contains one.
UNTYPED = ("FieldType::Raw", "FieldType::Skip")

HEADER = """\
//! Generated by `tools/extract_checksum_types.py` -- do not edit by hand.
//! `compatible_checksum` -> [`FieldType`], learned from the fields the overlay table types;
//! checksums whose donors disagree on the type are omitted.

{imports}
/// Sorted by checksum; binary-searched by `lookup_checksum`.
pub static CHECKSUM_TYPES: [(u32, FieldType); {count}] = [
"""

#: The `crate::types` names a rendered type can use. Each is imported only when
#: a row names it, because an unused `use` fails clippy's `-D warnings`.
QUANTIZATION_TYPES = ("RotatorQuantization", "VectorQuantization")


def normalize_type(ftype: str) -> str:
    """One spelling for a type in any layout: `RepMovement { a: X, b: Y }`."""
    return re.sub(r",\s*\}", " }", " ".join(ftype.split()))


def parse(path: Path, parser):
    """`parser` over one Rust table; a table that does not parse whole exits."""
    try:
        return parser(path.read_text(encoding="utf-8"))
    except overlay_mirror.ParseError as err:
        raise SystemExit(f"{path}: {err}") from err


def load_overlay_table() -> dict[tuple[str, str], str]:
    """`(group_path, field_name) -> type` for every OVERLAY_TABLE entry."""
    return {(g, n): normalize_type(t)
            for g, n, t in parse(TABLE_RS, overlay_mirror.overlay_entries)}


def learn(manifests: list[Path], table: dict[tuple[str, str], str]):
    """`(map, conflicts)` -- checksum to type, and the ones that disagreed."""
    seen: dict[int, set[str]] = collections.defaultdict(set)
    names: dict[int, set[str]] = collections.defaultdict(set)
    for path in manifests:
        manifest = json.loads(path.read_text(encoding="utf-8"))
        for group in manifest.get("net_field_export_groups") or []:
            group_path = group.get("path") or ""
            for field in group.get("fields") or []:
                checksum, name = field.get("compatible_checksum"), field.get("name")
                if checksum is None or not name:
                    continue
                names[checksum].add(name)
                declared = table.get((group_path, name))
                if declared and declared not in UNTYPED:
                    seen[checksum].add(declared)
    resolved = {c: next(iter(t)) for c, t in seen.items() if len(t) == 1}
    conflicts = {c: (sorted(t), sorted(names[c])) for c, t in seen.items() if len(t) > 1}
    return resolved, conflicts


def load_committed() -> dict[int, str]:
    """The committed checksum -> type map, `{}` before the first write."""
    if not OUT_RS.is_file():
        return {}
    return {c: normalize_type(t) for c, t in parse(OUT_RS, overlay_mirror.checksum_entries)}


@dataclasses.dataclass
class Verdict:
    """How a freshly learned map relates to the committed one.

    `new` and `unseen` are coverage: a wider basis teaches more of the same
    truth, a narrower one less. The other three fail `ok`: `disagreed` maps one
    checksum two ways. Of the committed checksums whose donors now conflict,
    `contradicted` ones are ruled out (the committed type is not among the
    candidates), and `ambiguous` ones are among them with no candidate safe.
    """

    disagreed: dict
    new: dict
    unseen: dict
    contradicted: dict = dataclasses.field(default_factory=dict)
    ambiguous: dict = dataclasses.field(default_factory=dict)

    @property
    def ok(self) -> bool:
        return not self.disagreed and not self.contradicted and not self.ambiguous


def _committed_vs_conflicts(committed: dict[int, str], conflicts: dict):
    """`(contradicted, ambiguous)` -- see `Verdict`."""
    contradicted, ambiguous = {}, {}
    for checksum, (types, names) in (conflicts or {}).items():
        if checksum not in committed:
            continue
        bucket = ambiguous if committed[checksum] in types else contradicted
        bucket[checksum] = (committed[checksum], types, names)
    return contradicted, ambiguous


def reconcile(committed: dict[int, str], learned: dict[int, str],
              conflicts: dict | None = None) -> Verdict:
    disagreed = {c: (committed[c], learned[c])
                 for c in committed.keys() & learned.keys()
                 if committed[c] != learned[c]}
    contradicted, ambiguous = _committed_vs_conflicts(committed, conflicts)
    return Verdict(
        disagreed,
        {c: learned[c] for c in learned.keys() - committed.keys()},
        {c: committed[c] for c in committed.keys() - learned.keys()},
        contradicted,
        ambiguous,
    )


def retype_problems(verdict: Verdict, retype: set[int]) -> list[str]:
    """Why a `--retype` request must be refused; empty when it may proceed.
    Only a real disagreement (the committed type against one unanimous learned
    type) can be retyped."""
    problems = []
    for checksum in sorted(retype):
        if checksum in verdict.disagreed:
            continue
        if checksum in verdict.contradicted or checksum in verdict.ambiguous:
            problems.append(f"{checksum}: its donors disagree among themselves, "
                            f"so there is no single type to retype it to")
        else:
            problems.append(f"{checksum}: the committed and learned types do not "
                            f"disagree under these manifests")
    return problems


def merge(committed: dict[int, str], learned: dict[int, str],
          conflicts: dict | None = None, retype=()) -> dict[int, str]:
    """Union, refusing a disagreement rather than picking a winner.

    An entry a narrower basis cannot re-derive is still correct, so it stays;
    a committed checksum in `conflicts` is dropped. `retype` names checksums
    whose learned type replaces the committed one; each must be learned, or it
    would vanish from the table instead.
    """
    retype = set(retype)
    unlearned = sorted(retype - learned.keys())
    if unlearned:
        raise ValueError(f"cannot retype {unlearned}: these manifests teach no type for it")
    committed = {c: t for c, t in committed.items() if c not in retype}
    clash = [c for c in committed.keys() & learned.keys()
             if committed[c] != learned[c]]
    if clash:
        raise ValueError(
            f"{len(clash)} checksum(s) disagree, refusing to merge: "
            + ", ".join(f"{c} {committed[c]} vs {learned[c]}"
                        for c in sorted(clash)[:5])
        )
    conflicted = set(conflicts or {})
    safe_committed = {c: t for c, t in committed.items() if c not in conflicted}
    return {**safe_committed, **learned}


def render(resolved: dict[int, str]) -> str:
    body = "".join(
        f"    ({checksum}, {resolved[checksum]}),\n" for checksum in sorted(resolved)
    )
    used = [name for name in QUANTIZATION_TYPES
            if any(f"{name}::" in ftype for ftype in resolved.values())]
    imports = "use crate::decode::FieldType;\n"
    if used:
        names = used[0] if len(used) == 1 else "{" + ", ".join(used) + "}"
        imports += f"use crate::types::{names};\n"
    header = HEADER.replace("{imports}", imports).replace("{count}", str(len(resolved)))
    return header + body + "];\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--export", type=Path, action="append", required=True,
                    help="directory written by `vrfkit export` (repeatable)")
    ap.add_argument("--check", action="store_true",
                    help="verify the committed file matches; write nothing")
    ap.add_argument("--retype", type=int, action="append", default=[],
                    metavar="CHECKSUM",
                    help="write mode: let the learned type replace the committed "
                         "one for this checksum (repeatable); refused unless the "
                         "two disagree")
    args = ap.parse_args()
    if args.retype and args.check:
        print("FAILED: --retype rewrites the table and has no meaning with --check",
              file=sys.stderr)
        return 2

    manifests = [d / "manifest.json" for d in args.export]
    missing = [m for m in manifests if not m.is_file()]
    if missing:
        print(f"FAILED: no manifest at {missing[0]}", file=sys.stderr)
        return 2

    table = load_overlay_table()
    resolved, conflicts = learn(manifests, table)

    for checksum, (types, names) in sorted(conflicts.items()):
        print(f"  dropped {checksum}: {names} declared as {types}")
    print(f"{len(table)} table entries, {len(manifests)} manifest(s) -> "
          f"{len(resolved)} checksums, {len(conflicts)} dropped")

    committed = load_committed()
    verdict = reconcile(committed, resolved, conflicts)
    print(f"vs committed: {len(verdict.disagreed)} disagree, {len(verdict.new)} "
          f"new here, {len(verdict.unseen)} not taught by these manifests, "
          f"{len(verdict.contradicted)} ruled out, {len(verdict.ambiguous)} now "
          f"ambiguous")
    for checksum, (was, now) in sorted(verdict.disagreed.items())[:10]:
        print(f"  DISAGREE {checksum}: committed {was}, learned {now}")
    for checksum, (was, types, names) in sorted(verdict.ambiguous.items())[:10]:
        print(f"  AMBIGUOUS {checksum} ({names}): committed {was}, donors now "
              f"disagree over {types} -- no candidate is safe")

    if args.check:
        if not verdict.ok:
            for checksum, (was, types, names) in sorted(
                    verdict.contradicted.items())[:10]:
                print(f"  RULED OUT {checksum} ({names}): committed {was}, "
                      f"donors declare {types}", file=sys.stderr)
            print(f"FAILED: {len(verdict.disagreed)} checksum(s) map two ways, "
                  f"{len(verdict.contradicted)} committed checksum(s) are ruled "
                  f"out, and {len(verdict.ambiguous)} are ambiguous under these "
                  f"manifests", file=sys.stderr)
            return 1
        print(f"\nOK: {OUT_RS.name} agrees with these manifests wherever they "
              f"overlap")
        return 0

    # Merge, never render fresh: that would drop what this basis did not see.
    problems = retype_problems(verdict, set(args.retype))
    if problems:
        for line in problems:
            print(f"  REFUSED --retype {line}", file=sys.stderr)
        print(f"FAILED: {len(problems)} --retype request(s) refused; nothing written",
              file=sys.stderr)
        return 1
    widened = merge(committed, resolved, conflicts, retype=args.retype)
    for checksum in sorted(set(args.retype)):
        print(f"  RETYPED {checksum}: {committed[checksum]} -> {widened[checksum]}")
    atomic_write_text(OUT_RS, render(widened))
    print(f"wrote {OUT_RS} ({len(widened)} checksums, +{len(verdict.new)}, "
          f"{len(set(args.retype))} retyped)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
