#!/usr/bin/env python3
"""Generate `crates/vrf-decode/src/checksum_table.rs` from export manifests.

Every `NetFieldExport` the replay declares carries a `compatible_checksum`, and
Unreal hashes the property's *type* into it alongside its name. That makes the
checksum a content address: two fields sharing one are the same property, even
on classes the C# descriptors never described.

So a parameter no descriptor declares can take its type from a declared field
with the same checksum. This script learns that map -- for every
`(group_path, field_name)` the overlay table already types, it records
`checksum -> FieldType` -- and emits it as a sorted static slice.

**A checksum is not replay-specific.** It is derived from the property, so the
map holds for any replay carrying the same property. Verified across all five
supported builds: `Scale3D` is 2983776962 on 12.10, 12.11, 13.00, 13.01 and
13.02 alike. That is what makes a generated table correct here, where a table
of *groups* would have been a snapshot of whichever match was exported.

**Conflicts are dropped, and that is the safety property.** A checksum whose
donors disagree on the type is not written, and an older committed answer is
removed as soon as a wider donor set makes it ambiguous. On the 1,018-replay
audit corpus that drops one: `ReplicatedMovement` (`ByteComponents` vs
`ShortComponents`, genuinely different and different in width) -- the case a
name-based rule would have got wrong.

It used to drop two. `AllianceFilter` (2270825073) had `EnumByte` donors and
one `EnumRemainingBits` donor, equivalent at the 3 bits every one of its
16,030,813 rows carries -- an inconsistency in the table, not on the wire, and
it left 4,560,248 receiver rows raw. `apply_type_corrections.py` now makes the
donors agree, so the checksum is learned; that is a fix to the donors, not an
exception to this rule.

Dropping decides what gets WRITTEN. It used to also end the story: the dropped
set never reached `reconcile`, so a checksum the file already commits and the
manifests now make unsafe passed `--check` and survived `merge`'s union. Every
committed conflict now fails checking and is omitted by write mode.

A committed type can only change on purpose. When a correction retypes the
donors of a checksum the file already carries -- `EffectID` from `UInt64` to
`Int64`, say -- the manifests teach the new type and `merge` refuses it as a
disagreement, which is right when nobody meant it. `--retype CHECKSUM` names
the checksums whose committed type the learned one may replace; it is refused
for a checksum that does not disagree (a stale or mistyped flag), for one
whose donors conflict among themselves, and in `--check`, which writes
nothing.

Usage:
    python tools/extract_checksum_types.py --export out/probe [--export out/other]
    python tools/extract_checksum_types.py --export out/probe --check
    python tools/extract_checksum_types.py --export out/probe --retype 1129645208
"""

from __future__ import annotations

import argparse
import collections
import json
import re
import sys
from pathlib import Path

if __package__:
    from .apply_type_corrections import normalize_type, parse_entries
    from .atomic_io import atomic_write_text
else:  # direct script execution
    from apply_type_corrections import normalize_type, parse_entries
    from atomic_io import atomic_write_text

REPO = Path(__file__).resolve().parents[1]
TABLE_RS = REPO / "crates" / "vrf-decode" / "src" / "table.rs"
OUT_RS = REPO / "crates" / "vrf-decode" / "src" / "checksum_table.rs"

#: Types that carry no decode, so propagating them buys a consumer nothing.
#: Compared whole: a substring test would also drop any type whose name merely
#: contains one of them.
UNTYPED = ("FieldType::Raw", "FieldType::Skip")

HEADER = """\
//! Generated by `tools/extract_checksum_types.py` -- do not edit by hand.
//!
//! `compatible_checksum` -> [`FieldType`], learned from the fields the overlay
//! table already types. Unreal hashes a property's type into its checksum, so
//! this identifies a property the way a name cannot: a parameter no descriptor
//! declares can take the type of a declared field sharing its checksum.
//!
//! Content-addressed and therefore build-stable -- the same property carries
//! the same checksum on 12.10 through 13.02. Checksums whose donors disagree on
//! the type are omitted, which is what keeps the mechanism from asserting the
//! cases it cannot settle.

{imports}
/// Sorted by checksum; binary-searched by `lookup_checksum`.
pub static CHECKSUM_TYPES: [(u32, FieldType); {count}] = [
"""

#: The `crate::types` names a rendered type can use. Each is imported only when
#: a row names it, because an unused `use` fails clippy's `-D warnings`.
QUANTIZATION_TYPES = ("RotatorQuantization", "VectorQuantization")


def load_overlay_table() -> dict[tuple[str, str], str]:
    """`(group_path, field_name) -> type`, read with apply_type_corrections'
    parser, so a braced type has one spelling in either layout (rustfmt adds
    a trailing comma inside it). That parser does not unescape, so a key
    holding an escape sequence is refused rather than silently unmatched."""
    table = {(group, field): ftype
             for group, field, ftype in parse_entries(TABLE_RS.read_text(encoding="utf-8"))}
    escaped = sorted(key for key in table if "\\" in key[0] or "\\" in key[1])
    if escaped:
        raise SystemExit(f"{TABLE_RS}: cannot read escaped keys {escaped[:3]}")
    return table


def learn(manifests: list[Path], table: dict[tuple[str, str], str]):
    """`(map, conflicts)` -- checksum to type, and the ones that disagreed."""
    seen: dict[int, set[str]] = collections.defaultdict(set)
    names: dict[int, set[str]] = collections.defaultdict(set)
    for path in manifests:
        manifest = json.loads(path.read_text(encoding="utf-8"))
        for group in manifest.get("net_field_export_groups") or []:
            group_path = group.get("path") or ""
            for field in group.get("fields") or []:
                checksum, name = field.get("compatible_checksum"), field.get("name")
                if checksum is None or not name:
                    continue
                names[checksum].add(name)
                declared = table.get((group_path, name))
                if declared and declared not in UNTYPED:
                    seen[checksum].add(declared)
    resolved = {c: next(iter(t)) for c, t in seen.items() if len(t) == 1}
    conflicts = {c: (sorted(t), sorted(names[c])) for c, t in seen.items() if len(t) > 1}
    return resolved, conflicts


#: One `(checksum, type)` row: on one line as `render` writes it, or broken
#: over lines by rustfmt when the type is long (`RepMovement { .. }`).
COMMITTED_RE = re.compile(
    r"\(\s*(\d+),\s*(FieldType::\w+(?:\s*\{[^{}]*\})?),?\s*\),")
COMMITTED_LEN_RE = re.compile(r"pub static CHECKSUM_TYPES: \[\(u32, FieldType\); (\d+)\]")


def load_committed() -> dict[int, str]:
    """The checksum -> type map as currently committed.

    Every row the slice declares must be read: a row the pattern misses would
    otherwise drop out of the comparison and out of the next write unseen.
    """
    if not OUT_RS.is_file():
        return {}
    src = OUT_RS.read_text(encoding="utf-8")
    rows = COMMITTED_RE.findall(src)
    committed = {int(c): normalize_type(t) for c, t in rows}
    declared = COMMITTED_LEN_RE.search(src)
    expected = int(declared.group(1)) if declared else None
    if expected is None or len(rows) != expected or len(committed) != expected:
        raise SystemExit(
            f"{OUT_RS}: declares {expected} rows, read {len(rows)} "
            f"({len(committed)} distinct checksums)"
        )
    return committed


class Verdict:
    """How a freshly learned map relates to the committed one.

    Five relations, and two of them are problems. `new` and `unseen` are both
    coverage: a checksum identifies a property, so a wider set of replays
    teaches a larger subset of the same truth and a narrower one teaches less.
    `disagreed` is the real thing -- one checksum mapped two ways, which means
    one of them is wrong.

    The last two come from the checksums `learn()` DROPPED. Dropping them is
    the safety property for what gets written, but it used to end the story:
    `conflicts` never reached this class, so a checksum the manifests now find
    ambiguous was compared against nothing and `--check` passed.

      `contradicted` the committed type is not among the candidate types at
                     all, so the new evidence rules it out. A problem.
      `ambiguous`    the committed type IS one of the candidates, but donors
                     disagree. No candidate remains safe, so this also fails.
    """

    def __init__(self, disagreed, new, unseen, contradicted=None, ambiguous=None):
        self.disagreed, self.new, self.unseen = disagreed, new, unseen
        self.contradicted = contradicted or {}
        self.ambiguous = ambiguous or {}

    @property
    def ok(self) -> bool:
        return not self.disagreed and not self.contradicted and not self.ambiguous


def _committed_vs_conflicts(committed: dict[int, str], conflicts: dict):
    """`(contradicted, ambiguous)` -- see `Verdict`."""
    contradicted, ambiguous = {}, {}
    for checksum, (types, names) in (conflicts or {}).items():
        if checksum not in committed:
            continue
        bucket = ambiguous if committed[checksum] in types else contradicted
        bucket[checksum] = (committed[checksum], types, names)
    return contradicted, ambiguous


def reconcile(committed: dict[int, str], learned: dict[int, str],
              conflicts: dict | None = None) -> Verdict:
    disagreed = {c: (committed[c], learned[c])
                 for c in committed.keys() & learned.keys()
                 if committed[c] != learned[c]}
    contradicted, ambiguous = _committed_vs_conflicts(committed, conflicts)
    return Verdict(
        disagreed,
        {c: learned[c] for c in learned.keys() - committed.keys()},
        {c: committed[c] for c in committed.keys() - learned.keys()},
        contradicted,
        ambiguous,
    )


def retype_problems(verdict: Verdict, retype: set[int]) -> list[str]:
    """Why a `--retype` request must be refused; empty when it may proceed.

    Only a real disagreement -- the committed type and one unanimous learned
    type -- can be retyped. Anything else is a flag that names the wrong
    checksum or a basis that cannot settle it.
    """
    problems = []
    for checksum in sorted(retype):
        if checksum in verdict.disagreed:
            continue
        if checksum in verdict.contradicted or checksum in verdict.ambiguous:
            problems.append(f"{checksum}: its donors disagree among themselves, "
                            f"so there is no single type to retype it to")
        else:
            problems.append(f"{checksum}: the committed and learned types do not "
                            f"disagree under these manifests")
    return problems


def merge(committed: dict[int, str], learned: dict[int, str],
          conflicts: dict | None = None, retype=()) -> dict[int, str]:
    """Union, refusing a disagreement rather than picking a winner.

    Widening the basis must not narrow the table: an entry a smaller run cannot
    re-derive is still correct, and a plain regeneration would silently drop it.

    Every key in `conflicts` is dropped from the old mapping. The write path
    heals an unsafe narrower-basis entry while preserving unrelated checksums
    this particular manifest set did not see.

    `retype` names checksums whose committed type the learned one replaces --
    the one deliberate exception to refusing a disagreement. Each must be
    learned, or it would silently vanish from the table instead.
    """
    retype = set(retype)
    unlearned = sorted(retype - learned.keys())
    if unlearned:
        raise ValueError(f"cannot retype {unlearned}: these manifests teach no type for it")
    committed = {c: t for c, t in committed.items() if c not in retype}
    clash = [c for c in committed.keys() & learned.keys()
             if committed[c] != learned[c]]
    if clash:
        raise ValueError(
            f"{len(clash)} checksum(s) disagree, refusing to merge: "
            + ", ".join(f"{c} {committed[c]} vs {learned[c]}"
                        for c in sorted(clash)[:5])
        )
    conflicted = set(conflicts or {})
    safe_committed = {c: t for c, t in committed.items() if c not in conflicted}
    return {**safe_committed, **learned}


def render(resolved: dict[int, str]) -> str:
    body = "".join(
        f"    ({checksum}, {resolved[checksum]}),\n" for checksum in sorted(resolved)
    )
    used = [name for name in QUANTIZATION_TYPES
            if any(f"{name}::" in ftype for ftype in resolved.values())]
    imports = "use crate::decode::FieldType;\n"
    if used:
        names = used[0] if len(used) == 1 else "{" + ", ".join(used) + "}"
        imports += f"use crate::types::{names};\n"
    header = HEADER.replace("{imports}", imports).replace("{count}", str(len(resolved)))
    return header + body + "];\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--export", type=Path, action="append", required=True,
                    help="directory written by `vrfkit export` (repeatable)")
    ap.add_argument("--check", action="store_true",
                    help="verify the committed file matches; write nothing")
    ap.add_argument("--retype", type=int, action="append", default=[],
                    metavar="CHECKSUM",
                    help="write mode: let the learned type replace the committed "
                         "one for this checksum (repeatable); refused unless the "
                         "two disagree")
    args = ap.parse_args()
    if args.retype and args.check:
        print("FAILED: --retype rewrites the table and has no meaning with --check",
              file=sys.stderr)
        return 2

    manifests = [d / "manifest.json" for d in args.export]
    missing = [m for m in manifests if not m.is_file()]
    if missing:
        print(f"FAILED: no manifest at {missing[0]}", file=sys.stderr)
        return 2

    table = load_overlay_table()
    if not table:
        print(f"FAILED: parsed no entries out of {TABLE_RS}", file=sys.stderr)
        return 1
    resolved, conflicts = learn(manifests, table)
    rendered = render(resolved)

    for checksum, (types, names) in sorted(conflicts.items()):
        print(f"  dropped {checksum}: {names} declared as {types}")
    print(f"{len(table)} table entries, {len(manifests)} manifest(s) -> "
          f"{len(resolved)} checksums, {len(conflicts)} dropped")

    committed = load_committed()
    verdict = reconcile(committed, resolved, conflicts)
    print(f"vs committed: {len(verdict.disagreed)} disagree, {len(verdict.new)} "
          f"new here, {len(verdict.unseen)} not taught by these manifests, "
          f"{len(verdict.contradicted)} ruled out, {len(verdict.ambiguous)} now "
          f"ambiguous")
    for checksum, (was, now) in sorted(verdict.disagreed.items())[:10]:
        print(f"  DISAGREE {checksum}: committed {was}, learned {now}")
    for checksum, (was, types, names) in sorted(verdict.ambiguous.items())[:10]:
        print(f"  AMBIGUOUS {checksum} ({names}): committed {was}, donors now "
              f"disagree over {types} -- no candidate is safe")

    if args.check:
        if not verdict.ok:
            for checksum, (was, types, names) in sorted(
                    verdict.contradicted.items())[:10]:
                print(f"  RULED OUT {checksum} ({names}): committed {was}, "
                      f"donors declare {types}", file=sys.stderr)
            print(f"FAILED: {len(verdict.disagreed)} checksum(s) map two ways, "
                  f"{len(verdict.contradicted)} committed checksum(s) are ruled "
                  f"out, and {len(verdict.ambiguous)} are ambiguous under these "
                  f"manifests", file=sys.stderr)
            return 1
        print(f"\nOK: {OUT_RS.name} agrees with these manifests wherever they "
              f"overlap")
        return 0

    # Merge rather than replace. A checksum this basis did not happen to see is
    # still correct, so rendering fresh would drop it -- which is how the file
    # came to hold 417 entries that no reachable export set reproduces. Byte
    # equality with a regeneration was never achievable for a content-addressed
    # table, and demanding it is what made `--check` fail for every basis and
    # stop meaning anything.
    problems = retype_problems(verdict, set(args.retype))
    if problems:
        for line in problems:
            print(f"  REFUSED --retype {line}", file=sys.stderr)
        print(f"FAILED: {len(problems)} --retype request(s) refused; nothing written",
              file=sys.stderr)
        return 1
    widened = merge(committed, resolved, conflicts, retype=args.retype)
    for checksum in sorted(set(args.retype)):
        print(f"  RETYPED {checksum}: {committed[checksum]} -> {widened[checksum]}")
    atomic_write_text(OUT_RS, render(widened))
    print(f"wrote {OUT_RS} ({len(widened)} checksums, +{len(verdict.new)}, "
          f"{len(set(args.retype))} retyped)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
