#!/usr/bin/env python3
"""Generate `crates/vrf-decode/src/checksum_table.rs` from export manifests.

Unreal hashes a property's *type* into each NetFieldExport's
`compatible_checksum`, beside its name, so the checksum is a content address:
fields sharing one are the same property, on any class and in any replay
(`Scale3D` is 2983776962 on each of the five builds checked: 12.10, 12.11,
13.00, 13.01, 13.02). That is why a generated table holds here, where a table
of groups would snapshot one match. A parameter no descriptor declares takes
the type of a declared field with the same checksum: for every
`(group_path, field_name)` the overlay table types, this records
`checksum -> FieldType`, emitted as a sorted static slice.

Conflicts are dropped; that is the safety property. A checksum whose donors
disagree is not written, and a committed entry they now make unsafe fails
`--check` and is omitted on write. On the 1,018-replay audit corpus the one
drop is `ReplicatedMovement` (`ByteComponents` vs `ShortComponents`, different
widths), the case a name rule would get wrong.

A committed type changes only on purpose. When a correction retypes the donors
of a committed checksum (`EffectID` from `UInt64` to `Int64`, say), `merge`
refuses the disagreement unless `--retype CHECKSUM` names it; `--retype` is
refused for a checksum that does not disagree, for one whose donors conflict,
and in `--check`, which writes nothing.

Usage:
    python tools/extract_checksum_types.py --export out/probe [--export out/other]
    python tools/extract_checksum_types.py --export out/probe --check
    python tools/extract_checksum_types.py --export out/probe --retype 1129645208
"""

from __future__ import annotations

import argparse
import collections
import dataclasses
import json
import re
import sys
from pathlib import Path

if __package__:
    from .apply_type_corrections import normalize_type, parse_entries
    from .atomic_io import atomic_write_text
else:  # direct script execution
    from apply_type_corrections import normalize_type, parse_entries
    from atomic_io import atomic_write_text

REPO = Path(__file__).resolve().parents[1]
TABLE_RS = REPO / "crates" / "vrf-decode" / "src" / "table.rs"
OUT_RS = REPO / "crates" / "vrf-decode" / "src" / "checksum_table.rs"

#: Types that carry no decode, so they teach nothing. Compared whole: a
#: substring test would also drop a type whose name merely contains one.
UNTYPED = ("FieldType::Raw", "FieldType::Skip")

HEADER = """\
//! Generated by `tools/extract_checksum_types.py` -- do not edit by hand.
//!
//! `compatible_checksum` -> [`FieldType`], learned from the fields the overlay
//! table already types. Unreal hashes a property's type into its checksum, so
//! this identifies a property the way a name cannot: a parameter no descriptor
//! declares can take the type of a declared field sharing its checksum.
//!
//! Content-addressed and therefore build-stable: the checksum follows the
//! property, not the build (`Scale3D` is 2983776962 on each of the five builds
//! checked, 12.10, 12.11, 13.00, 13.01 and 13.02). Checksums whose donors
//! disagree on the type are omitted, which is what keeps the mechanism from
//! asserting the cases it cannot settle.

{imports}
/// Sorted by checksum; binary-searched by `lookup_checksum`.
pub static CHECKSUM_TYPES: [(u32, FieldType); {count}] = [
"""

#: The `crate::types` names a rendered type can use. Each is imported only when
#: a row names it, because an unused `use` fails clippy's `-D warnings`.
QUANTIZATION_TYPES = ("RotatorQuantization", "VectorQuantization")


def load_overlay_table() -> dict[tuple[str, str], str]:
    """`(group_path, field_name) -> type` via apply_type_corrections' parser,
    so a braced type has one spelling in either layout. That parser does not
    unescape, so a key holding an escape is refused, not silently unmatched."""
    table = {(group, field): ftype
             for group, field, ftype in parse_entries(TABLE_RS.read_text(encoding="utf-8"))}
    escaped = sorted(key for key in table if "\\" in key[0] or "\\" in key[1])
    if escaped:
        raise SystemExit(f"{TABLE_RS}: cannot read escaped keys {escaped[:3]}")
    return table


def learn(manifests: list[Path], table: dict[tuple[str, str], str]):
    """`(map, conflicts)` -- checksum to type, and the ones that disagreed."""
    seen: dict[int, set[str]] = collections.defaultdict(set)
    names: dict[int, set[str]] = collections.defaultdict(set)
    for path in manifests:
        manifest = json.loads(path.read_text(encoding="utf-8"))
        for group in manifest.get("net_field_export_groups") or []:
            group_path = group.get("path") or ""
            for field in group.get("fields") or []:
                checksum, name = field.get("compatible_checksum"), field.get("name")
                if checksum is None or not name:
                    continue
                names[checksum].add(name)
                declared = table.get((group_path, name))
                if declared and declared not in UNTYPED:
                    seen[checksum].add(declared)
    resolved = {c: next(iter(t)) for c, t in seen.items() if len(t) == 1}
    conflicts = {c: (sorted(t), sorted(names[c])) for c, t in seen.items() if len(t) > 1}
    return resolved, conflicts


#: One `(checksum, type)` row: on one line as `render` writes it, or broken
#: over lines by rustfmt when the type is long (`RepMovement { .. }`).
COMMITTED_RE = re.compile(
    r"\(\s*(\d+),\s*(FieldType::\w+(?:\s*\{[^{}]*\})?),?\s*\),")
COMMITTED_LEN_RE = re.compile(r"pub static CHECKSUM_TYPES: \[\(u32, FieldType\); (\d+)\]")


def load_committed() -> dict[int, str]:
    """The committed checksum -> type map. Every row the slice declares must be
    read, or a missed row would leave the comparison and the next write unseen."""
    if not OUT_RS.is_file():
        return {}
    src = OUT_RS.read_text(encoding="utf-8")
    rows = COMMITTED_RE.findall(src)
    committed = {int(c): normalize_type(t) for c, t in rows}
    declared = COMMITTED_LEN_RE.search(src)
    expected = int(declared.group(1)) if declared else None
    if expected is None or len(rows) != expected or len(committed) != expected:
        raise SystemExit(
            f"{OUT_RS}: declares {expected} rows, read {len(rows)} "
            f"({len(committed)} distinct checksums)"
        )
    return committed


@dataclasses.dataclass
class Verdict:
    """How a freshly learned map relates to the committed one.

    `new` and `unseen` are coverage: a wider basis teaches more of the same
    truth, a narrower one less. The other three fail `ok`: `disagreed` maps one
    checksum two ways. Of the committed checksums whose donors now conflict,
    `contradicted` ones are ruled out (the committed type is not among the
    candidates), and `ambiguous` ones are among them with no candidate safe.
    """

    disagreed: dict
    new: dict
    unseen: dict
    contradicted: dict = dataclasses.field(default_factory=dict)
    ambiguous: dict = dataclasses.field(default_factory=dict)

    @property
    def ok(self) -> bool:
        return not self.disagreed and not self.contradicted and not self.ambiguous


def _committed_vs_conflicts(committed: dict[int, str], conflicts: dict):
    """`(contradicted, ambiguous)` -- see `Verdict`."""
    contradicted, ambiguous = {}, {}
    for checksum, (types, names) in (conflicts or {}).items():
        if checksum not in committed:
            continue
        bucket = ambiguous if committed[checksum] in types else contradicted
        bucket[checksum] = (committed[checksum], types, names)
    return contradicted, ambiguous


def reconcile(committed: dict[int, str], learned: dict[int, str],
              conflicts: dict | None = None) -> Verdict:
    disagreed = {c: (committed[c], learned[c])
                 for c in committed.keys() & learned.keys()
                 if committed[c] != learned[c]}
    contradicted, ambiguous = _committed_vs_conflicts(committed, conflicts)
    return Verdict(
        disagreed,
        {c: learned[c] for c in learned.keys() - committed.keys()},
        {c: committed[c] for c in committed.keys() - learned.keys()},
        contradicted,
        ambiguous,
    )


def retype_problems(verdict: Verdict, retype: set[int]) -> list[str]:
    """Why a `--retype` request must be refused; empty when it may proceed.
    Only a real disagreement (the committed type against one unanimous learned
    type) can be retyped."""
    problems = []
    for checksum in sorted(retype):
        if checksum in verdict.disagreed:
            continue
        if checksum in verdict.contradicted or checksum in verdict.ambiguous:
            problems.append(f"{checksum}: its donors disagree among themselves, "
                            f"so there is no single type to retype it to")
        else:
            problems.append(f"{checksum}: the committed and learned types do not "
                            f"disagree under these manifests")
    return problems


def merge(committed: dict[int, str], learned: dict[int, str],
          conflicts: dict | None = None, retype=()) -> dict[int, str]:
    """Union, refusing a disagreement rather than picking a winner.

    An entry a narrower basis cannot re-derive is still correct, so it stays;
    a committed checksum in `conflicts` is dropped. `retype` names checksums
    whose learned type replaces the committed one; each must be learned, or it
    would vanish from the table instead.
    """
    retype = set(retype)
    unlearned = sorted(retype - learned.keys())
    if unlearned:
        raise ValueError(f"cannot retype {unlearned}: these manifests teach no type for it")
    committed = {c: t for c, t in committed.items() if c not in retype}
    clash = [c for c in committed.keys() & learned.keys()
             if committed[c] != learned[c]]
    if clash:
        raise ValueError(
            f"{len(clash)} checksum(s) disagree, refusing to merge: "
            + ", ".join(f"{c} {committed[c]} vs {learned[c]}"
                        for c in sorted(clash)[:5])
        )
    conflicted = set(conflicts or {})
    safe_committed = {c: t for c, t in committed.items() if c not in conflicted}
    return {**safe_committed, **learned}


def render(resolved: dict[int, str]) -> str:
    body = "".join(
        f"    ({checksum}, {resolved[checksum]}),\n" for checksum in sorted(resolved)
    )
    used = [name for name in QUANTIZATION_TYPES
            if any(f"{name}::" in ftype for ftype in resolved.values())]
    imports = "use crate::decode::FieldType;\n"
    if used:
        names = used[0] if len(used) == 1 else "{" + ", ".join(used) + "}"
        imports += f"use crate::types::{names};\n"
    header = HEADER.replace("{imports}", imports).replace("{count}", str(len(resolved)))
    return header + body + "];\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--export", type=Path, action="append", required=True,
                    help="directory written by `vrfkit export` (repeatable)")
    ap.add_argument("--check", action="store_true",
                    help="verify the committed file matches; write nothing")
    ap.add_argument("--retype", type=int, action="append", default=[],
                    metavar="CHECKSUM",
                    help="write mode: let the learned type replace the committed "
                         "one for this checksum (repeatable); refused unless the "
                         "two disagree")
    args = ap.parse_args()
    if args.retype and args.check:
        print("FAILED: --retype rewrites the table and has no meaning with --check",
              file=sys.stderr)
        return 2

    manifests = [d / "manifest.json" for d in args.export]
    missing = [m for m in manifests if not m.is_file()]
    if missing:
        print(f"FAILED: no manifest at {missing[0]}", file=sys.stderr)
        return 2

    table = load_overlay_table()
    if not table:
        print(f"FAILED: parsed no entries out of {TABLE_RS}", file=sys.stderr)
        return 1
    resolved, conflicts = learn(manifests, table)
    rendered = render(resolved)

    for checksum, (types, names) in sorted(conflicts.items()):
        print(f"  dropped {checksum}: {names} declared as {types}")
    print(f"{len(table)} table entries, {len(manifests)} manifest(s) -> "
          f"{len(resolved)} checksums, {len(conflicts)} dropped")

    committed = load_committed()
    verdict = reconcile(committed, resolved, conflicts)
    print(f"vs committed: {len(verdict.disagreed)} disagree, {len(verdict.new)} "
          f"new here, {len(verdict.unseen)} not taught by these manifests, "
          f"{len(verdict.contradicted)} ruled out, {len(verdict.ambiguous)} now "
          f"ambiguous")
    for checksum, (was, now) in sorted(verdict.disagreed.items())[:10]:
        print(f"  DISAGREE {checksum}: committed {was}, learned {now}")
    for checksum, (was, types, names) in sorted(verdict.ambiguous.items())[:10]:
        print(f"  AMBIGUOUS {checksum} ({names}): committed {was}, donors now "
              f"disagree over {types} -- no candidate is safe")

    if args.check:
        if not verdict.ok:
            for checksum, (was, types, names) in sorted(
                    verdict.contradicted.items())[:10]:
                print(f"  RULED OUT {checksum} ({names}): committed {was}, "
                      f"donors declare {types}", file=sys.stderr)
            print(f"FAILED: {len(verdict.disagreed)} checksum(s) map two ways, "
                  f"{len(verdict.contradicted)} committed checksum(s) are ruled "
                  f"out, and {len(verdict.ambiguous)} are ambiguous under these "
                  f"manifests", file=sys.stderr)
            return 1
        print(f"\nOK: {OUT_RS.name} agrees with these manifests wherever they "
              f"overlap")
        return 0

    # Merge, never render fresh: that would drop what this basis did not see.
    problems = retype_problems(verdict, set(args.retype))
    if problems:
        for line in problems:
            print(f"  REFUSED --retype {line}", file=sys.stderr)
        print(f"FAILED: {len(problems)} --retype request(s) refused; nothing written",
              file=sys.stderr)
        return 1
    widened = merge(committed, resolved, conflicts, retype=args.retype)
    for checksum in sorted(set(args.retype)):
        print(f"  RETYPED {checksum}: {committed[checksum]} -> {widened[checksum]}")
    atomic_write_text(OUT_RS, render(widened))
    print(f"wrote {OUT_RS} ({len(widened)} checksums, +{len(verdict.new)}, "
          f"{len(set(args.retype))} retyped)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
